export const discoveryClubsDetailBodySectionStyles = {
  root: "flex flex-col gap-8 px-5 pb-4 pt-4",
  section: "flex flex-col gap-3",
  sectionHeader: "flex items-center justify-between gap-3",
  sectionTitle: "min-w-0 flex-1 text-foreground",
  statsBar: [
    "flex w-full items-stretch overflow-hidden rounded-[1.75rem]",
    "border border-border/70 bg-default",
  ].join(" "),
  statCell: [
    "relative flex min-w-0 flex-1 flex-col items-center justify-center gap-2",
    "px-2 py-5",
    "after:absolute after:end-0 after:top-[18%] after:bottom-[18%] after:w-px after:bg-border",
    "last:after:hidden",
  ].join(" "),
  statValue: "text-[1.65rem] leading-none tracking-tight text-foreground",
  statMeta: "flex items-center gap-1.5 text-muted",
  statIcon: "shrink-0",
  statIconMuted: "text-muted",
  statIconScore: "text-warning",
  statIconTasks: "text-accent",
  statLabel: "text-[0.8rem] leading-none text-muted",
  bodyText: "text-sm leading-relaxed text-muted",
  descriptionWrap: "relative",
  descriptionClamped: "line-clamp-3",
  seeMoreFade: [
    "pointer-events-none absolute inset-x-0 bottom-0 z-10",
    "flex items-end justify-center pb-0.5 pt-10",
    "bg-linear-to-t from-surface via-surface/90 to-transparent",
  ].join(" "),
  seeMoreTrigger: "pointer-events-auto",
  seeLess: "mt-2 flex self-start",
  carousel: [
    "min-w-0 -mx-5 w-[calc(100%+2.5rem)] max-w-none overflow-hidden",
    "[-ms-overflow-style:none] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden pe-[calc(env(safe-area-inset-right)+1rem)]",
  ].join(" "),
  carouselTrack: "flex touch-pan-y gap-3 px-5 pb-1",
  slide: "min-w-0 shrink-0",
  reviewSlide: "w-[min(20rem,calc(100vw-3.5rem))] min-w-0 shrink-0",
  equipmentDrawerBody: "overflow-hidden",
  equipmentDrawerScroll: "max-h-[min(65dvh,32rem)]",
  equipmentDrawerList: "flex flex-col gap-2.5 pb-1",
  equipmentSeeAll: [
    "flex h-[148px] w-[144px] shrink-0 snap-start flex-col items-center justify-center gap-2",
    "rounded-[24px] border border-border/70 bg-default text-foreground",
    "transition-transform duration-fast ease-app",
    "data-[pressed=true]:scale-[0.98]",
  ].join(" "),
  sportSeeAll: [
    "flex h-[270px] w-[200px] shrink-0 snap-start flex-col items-center justify-center gap-3",
    "rounded-[24px] border border-border/70 bg-default text-foreground",
    "transition-transform duration-fast ease-app",
    "data-[pressed=true]:scale-[0.98]",
  ].join(" "),
  branchSeeAll: [
    "flex h-[360px] w-[200px] shrink-0 snap-start flex-col items-center justify-center gap-3",
    "rounded-[36px] border border-border/70 bg-default text-foreground",
    "transition-transform duration-fast ease-app",
    "data-[pressed=true]:scale-[0.98]",
  ].join(" "),
  classSeeAll: [
    "flex h-[346px] w-[280px] shrink-0 snap-start flex-col items-center justify-center gap-3",
    "rounded-[32px] border border-border/70 bg-default text-foreground",
    "transition-transform duration-fast ease-app",
    "data-[pressed=true]:scale-[0.98]",
  ].join(" "),
  reviewSeeAll: [
    "flex h-full min-h-[220px] w-[min(12rem,calc(100vw-3.5rem))] shrink-0 snap-start",
    "flex-col items-center justify-center gap-3",
    "rounded-[32px] border border-border/70 bg-default text-foreground",
    "transition-transform duration-fast ease-app",
    "data-[pressed=true]:scale-[0.98]",
  ].join(" "),
  seeAllLabel: "text-center text-sm font-semibold",
  classSeeAllLabel: "text-center text-base font-semibold",
  busyHoursChart: [
    "rounded-[1.5rem] border border-border/60 bg-default px-3 pb-3 pt-4",
  ].join(" "),
  reviewCard: "h-full border border-border/70 bg-default",
  subscriptionGroup: "flex w-full flex-col gap-4",
  subscriptionRadio: [
    "w-full overflow-visible border-0 bg-transparent p-0 shadow-none",
    "data-[selected=true]:bg-transparent",
  ].join(" "),
  subscriptionContent: [
    "group w-full gap-0 bg-transparent p-0 shadow-none",
    "hover:bg-transparent data-[hovered=true]:bg-transparent",
    "data-[selected=true]:bg-transparent data-[selected=true]:data-[hovered=true]:bg-transparent",
    "pressed:bg-transparent data-[pressed=true]:bg-transparent",
  ].join(" "),
  subscriptionControl: [
    "flex size-8 shrink-0 items-center justify-center rounded-full border-2 border-accent",
    "bg-transparent text-accent-foreground shadow-none",
    "group-data-[selected=true]:border-transparent group-data-[selected=true]:bg-accent",
    "group-data-[selected=true]:text-accent-foreground",
    "group-data-[pressed=true]:scale-95",
  ].join(" "),
  subscriptionIndicator:
    "flex items-center justify-center text-current [&_svg]:size-[18px]",
} as const;
