export const discoveryCoachesReserveScreenStyles = {
  root: "relative flex min-h-dvh flex-col bg-background",
  scroll: "flex-1 overflow-y-auto pb-36",
  main: "flex flex-col gap-6 px-5 pt-4",
  coachRow: "flex items-center gap-3",
  avatar: "size-14 shrink-0",
  coachMeta: "flex min-w-0 flex-1 flex-col gap-0.5",
  coachName: "truncate text-foreground",
  coachSpecialty: "truncate text-muted",
  rating: "flex items-center gap-1",
  ratingValue: "text-foreground",
  ratingStar: "text-warning",
  stepPanel: "flex flex-col gap-6",
  section: "flex flex-col gap-3",
  sectionTitle: "text-foreground",
  sectionHint: "text-muted",
  fields: "flex flex-col gap-4",
  chips: "flex flex-wrap gap-2",
  noteCount: "self-end text-muted",
  weekRow: "flex items-center justify-between",
  weekLabel: "text-foreground",
  weekNav: "flex items-center gap-2",
  weekButton: "size-10 rounded-full bg-surface-secondary text-foreground",
  weekButtonIcon: "text-foreground",
  locationCard:
    "flex flex-col gap-1 rounded-2xl border border-separator bg-surface-secondary p-4",
  locationTitle: "text-foreground",
  locationAddress: "text-muted",
  remoteHint:
    "rounded-2xl border border-separator bg-surface-secondary p-4 text-muted",
  summaryCard:
    "flex flex-col gap-3 rounded-2xl border border-separator bg-surface-secondary p-4",
  summaryRow: "flex items-center justify-between gap-3",
  summaryLabel: "text-muted",
  summaryValue: "text-foreground",
  summaryTotalRow: "border-t border-separator pt-3",
  summaryTotalValue: "text-foreground",
  couponRow: "flex items-end gap-2",
  couponField: "flex-1",
  couponApply: "shrink-0",
  methodCard:
    "flex items-center justify-between gap-3 rounded-2xl border border-accent bg-accent/5 p-4",
  methodBody: "flex min-w-0 flex-col gap-0.5",
  methodTitle: "text-foreground",
  methodHint: "text-muted",
  methodCheck: "text-accent",
  errorText: "text-danger",
  emptySlots:
    "rounded-2xl border border-dashed border-separator p-6 text-center text-muted",
  footerRow: "flex items-center justify-between gap-3",
  priceGroup: "flex min-w-0 flex-col",
  priceLabel: "text-muted",
  priceRow: "flex items-baseline gap-1",
  price: "text-xl font-bold text-foreground",
  priceSuffix: "text-xs text-muted",
  confirm: "min-w-40 shrink-0",
  confirmLabel: "text-primary-foreground",
} as const;
