import { RefType } from '../../common/enums';

export type RefDefaultItem = {
  name: string;
  slug: string;
  /** PascalCase `@repo/icons` catalog name */
  icon?: string;
  order?: number;
};

const withOrder = (items: Omit<RefDefaultItem, 'order'>[]): RefDefaultItem[] =>
  items.map((item, order) => ({ ...item, order }));

/** Practical Persian launch catalog used by the admin "Import defaults" action. */
export const DEFAULT_REFS: Record<RefType, RefDefaultItem[]> = {
  [RefType.AMENITY]: withOrder([
    { name: 'پارکینگ', slug: 'parking', icon: 'Car1' },
    { name: 'پارکینگ دوچرخه', slug: 'bicycle-parking', icon: 'Bicycle' },
    { name: 'دوش', slug: 'shower', icon: 'Shower1' },
    { name: 'رختکن', slug: 'changing-room', icon: 'PersonMan1' },
    { name: 'کمد امانات', slug: 'locker', icon: 'Lock1' },
    { name: 'سرویس بهداشتی', slug: 'restroom' },
    { name: 'سونا خشک', slug: 'dry-sauna', icon: 'Sun' },
    { name: 'سونا بخار', slug: 'steam-sauna', icon: 'Sun' },
    { name: 'سونا', slug: 'sauna', icon: 'Sun' },
    { name: 'جکوزی', slug: 'jacuzzi', icon: 'PersonSwimming' },
    { name: 'استخر', slug: 'pool', icon: 'PersonSwimming' },
    { name: 'استخر کودکان', slug: 'kids-pool', icon: 'PersonSwimming' },
    { name: 'آب‌سردکن', slug: 'water-dispenser' },
    { name: 'بوفه و کافه', slug: 'cafe', icon: 'Coffee' },
    { name: 'فروشگاه ورزشی', slug: 'sports-shop' },
    { name: 'وای‌فای', slug: 'wifi', icon: 'WifiFull' },
    { name: 'تهویه مطبوع', slug: 'air-conditioning' },
    { name: 'گرمایش', slug: 'heating', icon: 'Sun' },
    { name: 'فضای استراحت', slug: 'lounge', icon: 'Bed' },
    { name: 'اتاق کودک', slug: 'childcare' },
    { name: 'اتاق ماساژ', slug: 'massage-room', icon: 'HandHeart' },
    {
      name: 'اتاق کمک‌های اولیه',
      slug: 'first-aid-room',
      icon: 'HeartWellness1',
    },
    { name: 'مربی مستقر', slug: 'on-site-coach', icon: 'PersonArmsSpread' },
    { name: 'پذیرش شبانه‌روزی', slug: '24-hour-reception', icon: 'Clock' },
    { name: 'فعالیت ۲۴ ساعته', slug: 'open-24-hours', icon: 'Clock' },
    { name: 'دسترسی آسانسور', slug: 'elevator-access' },
    { name: 'دسترسی‌پذیری', slug: 'accessibility', icon: 'Wheelchair' },
    { name: 'دسترسی ویلچر', slug: 'wheelchair-access', icon: 'Wheelchair' },
    {
      name: 'سرویس بهداشتی دسترس‌پذیر',
      slug: 'accessible-restroom',
      icon: 'Wheelchair',
    },
    { name: 'نمازخانه', slug: 'prayer-room' },
    { name: 'فضای روباز', slug: 'outdoor-area', icon: 'Sun' },
    { name: 'سیستم صوتی', slug: 'sound-system' },
    { name: 'تهیه حوله', slug: 'towel-service' },
    { name: 'لوازم بهداشتی', slug: 'toiletries', icon: 'Sparkle1' },
    { name: 'خشک‌کن مو', slug: 'hair-dryer' },
    { name: 'ترازو و آنالیز بدن', slug: 'body-analysis', icon: 'WeightScale' },
    { name: 'پخش آنلاین کلاس', slug: 'class-streaming', icon: 'WifiFull' },
    {
      name: 'امنیت و دوربین مداربسته',
      slug: 'security-camera',
      icon: 'ShieldCheck',
    },
  ]),
  [RefType.EQUIPMENT]: withOrder([
    { name: 'دمبل', slug: 'dumbbell', icon: 'Weight' },
    { name: 'هالتر', slug: 'barbell', icon: 'BarbellHorizontal' },
    { name: 'صفحه وزنه', slug: 'weight-plate', icon: 'Weight' },
    { name: 'کتل‌بل', slug: 'kettlebell', icon: 'Weight' },
    { name: 'نیمکت بدنسازی', slug: 'weight-bench', icon: 'BarbellHorizontal' },
    { name: 'رک اسکوات', slug: 'squat-rack', icon: 'BarbellHorizontal' },
    { name: 'اسمیت ماشین', slug: 'smith-machine', icon: 'BarbellHorizontal' },
    { name: 'دستگاه سیم‌کش', slug: 'cable-machine', icon: 'Weight' },
    { name: 'دستگاه پرس سینه', slug: 'chest-press-machine', icon: 'Bicep' },
    { name: 'دستگاه پرس پا', slug: 'leg-press-machine', icon: 'Weight' },
    { name: 'دستگاه جلوپا', slug: 'leg-extension-machine', icon: 'Weight' },
    { name: 'دستگاه پشت‌پا', slug: 'leg-curl-machine', icon: 'Weight' },
    { name: 'دستگاه لت', slug: 'lat-pulldown-machine', icon: 'Bicep' },
    { name: 'دستگاه قایقی', slug: 'seated-row-machine', icon: 'PersonRowing' },
    { name: 'دستگاه ساق پا', slug: 'calf-raise-machine', icon: 'Weight' },
    { name: 'بارفیکس', slug: 'pull-up-bar', icon: 'PersonArmsSpread' },
    { name: 'پارالل', slug: 'dip-station', icon: 'PersonArmsSpread' },
    { name: 'تردمیل', slug: 'treadmill', icon: 'Treadmill' },
    { name: 'دوچرخه ثابت', slug: 'stationary-bike', icon: 'Bicycle' },
    { name: 'دوچرخه اسپینینگ', slug: 'spin-bike', icon: 'PersonBiking' },
    { name: 'الپتیکال', slug: 'elliptical' },
    { name: 'استپ‌میل', slug: 'stair-climber' },
    { name: 'دستگاه روئینگ', slug: 'rowing-machine', icon: 'PersonRowing' },
    { name: 'ایربایک', slug: 'air-bike', icon: 'Bicycle' },
    { name: 'طناب ورزشی', slug: 'jump-rope' },
    { name: 'بتل روپ', slug: 'battle-rope' },
    { name: 'کش مقاومتی', slug: 'resistance-band', icon: 'Bicep' },
    {
      name: 'کش تی‌آر‌ایکس',
      slug: 'suspension-trainer',
      icon: 'PersonArmsSpread',
    },
    { name: 'توپ مدیسین', slug: 'medicine-ball', icon: 'Soccer' },
    { name: 'توپ سوئیسی', slug: 'stability-ball' },
    { name: 'بوسوبال', slug: 'bosu-ball' },
    { name: 'باکس پرش', slug: 'plyo-box' },
    { name: 'سورتمه تمرینی', slug: 'training-sled' },
    { name: 'فوم رولر', slug: 'foam-roller' },
    { name: 'مت ورزشی', slug: 'exercise-mat', icon: 'PersonYoga' },
    { name: 'پیلاتس ریفورمر', slug: 'pilates-reformer', icon: 'PersonYoga' },
    { name: 'کیسه بوکس', slug: 'punching-bag', icon: 'Boxing' },
    { name: 'رینگ بوکس', slug: 'boxing-ring', icon: 'Boxing' },
    { name: 'تاتامی', slug: 'tatami', icon: 'PersonKarate' },
    { name: 'میت و پد رزمی', slug: 'combat-pads', icon: 'Boxing' },
    { name: 'میز پینگ‌پنگ', slug: 'table-tennis-table', icon: 'Tennis1' },
    { name: 'تور و پایه والیبال', slug: 'volleyball-net', icon: 'Volleyball' },
    { name: 'حلقه بسکتبال', slug: 'basketball-hoop', icon: 'Basketball' },
    { name: 'دروازه فوتبال', slug: 'football-goal', icon: 'Soccer' },
    { name: 'راکت تنیس', slug: 'tennis-racket', icon: 'Tennis' },
    { name: 'راکت بدمینتون', slug: 'badminton-racket', icon: 'Tennis1' },
    { name: 'لوازم شنا', slug: 'swimming-aids', icon: 'PersonSwimming' },
    {
      name: 'تجهیزات صخره‌نوردی',
      slug: 'climbing-equipment',
      icon: 'PersonHiking',
    },
    { name: 'تجهیزات اسکی', slug: 'ski-equipment' },
    {
      name: 'موانع و نردبان چابکی',
      slug: 'agility-equipment',
      icon: 'PersonRunning',
    },
    { name: 'کرنومتر و تایمر', slug: 'training-timer', icon: 'Clock' },
    { name: 'ترازو', slug: 'scale', icon: 'WeightScale' },
    {
      name: 'دستگاه آنالیز ترکیب بدن',
      slug: 'body-composition-analyzer',
      icon: 'BodyFat',
    },
  ]),
  [RefType.MUSCLE]: withOrder([
    { name: 'سینه', slug: 'chest', icon: 'Heart' },
    { name: 'پشت', slug: 'back', icon: 'PersonArmsSpread' },
    { name: 'سرشانه', slug: 'shoulders', icon: 'PersonArmsSpread' },
    { name: 'جلو بازو', slug: 'biceps', icon: 'Bicep' },
    { name: 'پشت بازو', slug: 'triceps', icon: 'Bicep' },
    { name: 'ساعد', slug: 'forearms', icon: 'Bicep' },
    { name: 'شکم و میان‌تنه', slug: 'core', icon: 'Target1' },
    { name: 'پا', slug: 'legs', icon: 'PersonRunning' },
    { name: 'سرینی', slug: 'glutes', icon: 'PersonRunning' },
    { name: 'چهارسر ران', slug: 'quadriceps', icon: 'PersonRunning' },
    { name: 'همسترینگ', slug: 'hamstrings', icon: 'PersonRunning' },
    { name: 'ساق پا', slug: 'calves', icon: 'PersonRunning' },
    { name: 'کل بدن', slug: 'full-body', icon: 'PersonArmsSpread' },
  ]),
  [RefType.GOAL_TYPE]: withOrder([
    {
      name: 'کاهش وزن و چربی‌سوزی',
      slug: 'weight-loss',
      icon: 'WeightScaleMinus',
    },
    {
      name: 'افزایش وزن سالم',
      slug: 'healthy-weight-gain',
      icon: 'WeightScalePlus',
    },
    { name: 'عضله‌سازی', slug: 'muscle-gain', icon: 'Bicep' },
    { name: 'افزایش قدرت', slug: 'strength', icon: 'BarbellHorizontal' },
    { name: 'افزایش استقامت', slug: 'endurance', icon: 'PersonRunning' },
    {
      name: 'بهبود آمادگی قلبی‌تنفسی',
      slug: 'cardio-fitness',
      icon: 'HeartWellness1',
    },
    { name: 'افزایش انعطاف‌پذیری', slug: 'flexibility', icon: 'PersonYoga' },
    {
      name: 'اصلاح فرم بدن و پاسچر',
      slug: 'posture',
      icon: 'PersonArmsSpread',
    },
    { name: 'بهبود تحرک و تعادل', slug: 'mobility-balance', icon: 'Balance' },
    { name: 'آمادگی برای مسابقه', slug: 'competition', icon: 'Trophy1' },
    { name: 'بهبود عملکرد ورزشی', slug: 'sports-performance', icon: 'Target1' },
    {
      name: 'بازگشت به ورزش پس از آسیب',
      slug: 'return-to-sport',
      icon: 'PersonInjured',
    },
    {
      name: 'کاهش استرس و سلامت ذهن',
      slug: 'stress-relief',
      icon: 'PersonMeditation',
    },
    {
      name: 'سلامت عمومی و سبک زندگی فعال',
      slug: 'general-health',
      icon: 'HeartWellness1',
    },
    { name: 'حفظ تناسب اندام', slug: 'maintenance', icon: 'CheckCircle' },
    {
      name: 'یادگیری یک رشته ورزشی',
      slug: 'learn-a-sport',
      icon: 'AcademicCap',
    },
  ]),
  [RefType.CLUB_CATEGORY]: withOrder([
    {
      name: 'باشگاه بدنسازی و تناسب اندام',
      slug: 'gym',
      icon: 'BarbellHorizontal',
    },
    { name: 'باشگاه بانوان', slug: 'womens-gym', icon: 'PersonWoman1' },
    { name: 'باشگاه آقایان', slug: 'mens-gym', icon: 'PersonMan1' },
    {
      name: 'استودیو تمرین خصوصی',
      slug: 'personal-training-studio',
      icon: 'PersonArmsSpread',
    },
    { name: 'استودیو کلاس گروهی', slug: 'group-class', icon: 'UsersThree' },
    { name: 'استودیو یوگا و مدیتیشن', slug: 'yoga-studio', icon: 'PersonYoga' },
    { name: 'استودیو پیلاتس', slug: 'pilates-studio', icon: 'PersonYoga' },
    { name: 'باکس کراس‌فیت', slug: 'crossfit-box', icon: 'Weight' },
    { name: 'باشگاه رزمی', slug: 'martial-arts-club', icon: 'PersonKarate' },
    { name: 'باشگاه بوکس', slug: 'boxing-gym', icon: 'Boxing' },
    { name: 'مجموعه آبی و استخر', slug: 'pool', icon: 'PersonSwimming' },
    {
      name: 'سالن سرپوشیده چندمنظوره',
      slug: 'indoor-arena',
      icon: 'Building2',
    },
    { name: 'زمین فوتبال و فوتسال', slug: 'football', icon: 'SoccerField' },
    {
      name: 'مجموعه ورزش‌های راکتی',
      slug: 'racket-sports-club',
      icon: 'Tennis',
    },
    { name: 'باشگاه سوارکاری', slug: 'equestrian-club', icon: 'PersonHiking' },
    { name: 'باشگاه تیراندازی', slug: 'shooting-club', icon: 'Archery' },
    { name: 'باشگاه سنگ‌نوردی', slug: 'climbing-gym', icon: 'PersonHiking' },
    { name: 'باشگاه دوچرخه‌سواری', slug: 'cycling-club', icon: 'Bicycle' },
    {
      name: 'باشگاه کوهنوردی و طبیعت‌گردی',
      slug: 'outdoor-club',
      icon: 'PersonHiking',
    },
    {
      name: 'باشگاه ورزش‌های زمستانی',
      slug: 'winter-sports-club',
      icon: 'IceSkating',
    },
    {
      name: 'آکادمی ورزشی کودکان',
      slug: 'kids-sports-academy',
      icon: 'PersonAcrobatics',
    },
    {
      name: 'مرکز توان‌بخشی و تمرین درمانی',
      slug: 'rehab-fitness-center',
      icon: 'PersonInjured',
    },
    { name: 'مجموعه ورزشی چندرشته‌ای', slug: 'multi-sport', icon: 'Building2' },
    { name: 'زورخانه', slug: 'zurkhaneh', icon: 'PersonKarate' },
    { name: 'باشگاه کشتی', slug: 'wrestling-club', icon: 'PersonKarate' },
    {
      name: 'استودیو رقص و ایروبیک',
      slug: 'dance-studio',
      icon: 'PersonAcrobatics',
    },
    {
      name: 'سالن ژیمناستیک',
      slug: 'gymnastics-academy',
      icon: 'PersonAcrobatics',
    },
    {
      name: 'باشگاه وزنه‌برداری',
      slug: 'weightlifting-club',
      icon: 'BarbellHorizontal',
    },
    {
      name: 'استودیو تمرین عملکردی',
      slug: 'functional-studio',
      icon: 'PersonArmsSpread',
    },
    { name: 'باشگاه پدل', slug: 'padel-club', icon: 'Tennis' },
    { name: 'سالن اسکواش', slug: 'squash-club', icon: 'Tennis' },
    { name: 'سالن والیبال', slug: 'volleyball-hall', icon: 'Volleyball' },
    { name: 'سالن بسکتبال', slug: 'basketball-court', icon: 'Basketball' },
    { name: 'پیست بولینگ', slug: 'bowling-alley', icon: 'PersonDodgeball' },
    { name: 'پیست یخ و پاتیناژ', slug: 'ice-rink', icon: 'IceSkating' },
    { name: 'مرکز اسپا و سلامت', slug: 'spa-wellness', icon: 'HandHeart' },
    { name: 'باشگاه گلف', slug: 'golf-club', icon: 'Golf' },
  ]),
  [RefType.REVIEW_CRITERION]: withOrder([
    {
      name: 'نحوه پذیرش و برخورد کارکنان',
      slug: 'check-in',
      icon: 'ShieldCheck',
    },
    { name: 'نظافت و بهداشت', slug: 'cleanliness', icon: 'Sparkle1' },
    {
      name: 'کیفیت و سلامت تجهیزات',
      slug: 'equipment-quality',
      icon: 'BarbellHorizontal',
    },
    { name: 'فضا و امکانات', slug: 'facilities', icon: 'Building2' },
    { name: 'تطابق با اطلاعات ثبت‌شده', slug: 'accuracy', icon: 'CheckCircle' },
    {
      name: 'کیفیت مربی و آموزش',
      slug: 'coaching-quality',
      icon: 'AcademicCap',
    },
    { name: 'برنامه‌ریزی و وقت‌شناسی', slug: 'punctuality', icon: 'Clock' },
    { name: 'ازدحام و ظرفیت', slug: 'crowding', icon: 'UsersThree' },
    { name: 'ایمنی', slug: 'safety', icon: 'ShieldCheck' },
    { name: 'موقعیت مکانی و دسترسی', slug: 'location', icon: 'MapPin2' },
    { name: 'ارزش خرید نسبت به قیمت', slug: 'value', icon: 'Wallet' },
    { name: 'تجربه کلی', slug: 'overall-experience', icon: 'Heart' },
    { name: 'نحوه میزبانی', slug: 'hosting', icon: 'HandHeart' },
  ]),
  [RefType.COACH_SPECIALTY]: withOrder([
    { name: 'بدنسازی و عضله‌سازی', slug: 'bodybuilding', icon: 'Bicep' },
    {
      name: 'تمرین قدرتی',
      slug: 'strength-training',
      icon: 'BarbellHorizontal',
    },
    {
      name: 'کاهش وزن و چربی‌سوزی',
      slug: 'weight-loss',
      icon: 'WeightScaleMinus',
    },
    {
      name: 'تمرین عملکردی',
      slug: 'functional-training',
      icon: 'PersonArmsSpread',
    },
    { name: 'کراس‌فیت', slug: 'crossfit', icon: 'Weight' },
    {
      name: 'تمرینات هوازی و استقامتی',
      slug: 'cardio-endurance',
      icon: 'PersonRunning',
    },
    {
      name: 'آمادگی جسمانی عمومی',
      slug: 'general-fitness',
      icon: 'HeartWellness1',
    },
    {
      name: 'اصلاحی و بهبود پاسچر',
      slug: 'corrective-exercise',
      icon: 'PersonArmsSpread',
    },
    {
      name: 'بازتوانی ورزشی',
      slug: 'sports-rehabilitation',
      icon: 'PersonInjured',
    },
    { name: 'یوگا', slug: 'yoga', icon: 'PersonYoga' },
    { name: 'پیلاتس', slug: 'pilates', icon: 'PersonYoga' },
    {
      name: 'مدیتیشن و تنفس',
      slug: 'meditation-breathwork',
      icon: 'PersonMeditation',
    },
    { name: 'فوتبال و فوتسال', slug: 'football-futsal', icon: 'Soccer' },
    { name: 'والیبال', slug: 'volleyball', icon: 'Volleyball' },
    { name: 'بسکتبال', slug: 'basketball', icon: 'Basketball' },
    { name: 'ورزش‌های راکتی', slug: 'racket-sports', icon: 'Tennis' },
    {
      name: 'شنا و ورزش‌های آبی',
      slug: 'swimming-aquatics',
      icon: 'PersonSwimming',
    },
    { name: 'بوکس و کیک‌بوکسینگ', slug: 'boxing-kickboxing', icon: 'Boxing' },
    { name: 'هنرهای رزمی', slug: 'martial-arts', icon: 'PersonKarate' },
    { name: 'دو و آمادگی مسابقه', slug: 'running', icon: 'PersonRunning' },
    { name: 'دوچرخه‌سواری', slug: 'cycling', icon: 'Bicycle' },
    {
      name: 'کوهنوردی و آمادگی فضای باز',
      slug: 'outdoor-conditioning',
      icon: 'PersonHiking',
    },
    {
      name: 'کودکان و نوجوانان',
      slug: 'youth-fitness',
      icon: 'PersonAcrobatics',
    },
    { name: 'سالمندان', slug: 'senior-fitness', icon: 'PersonElderlyMale' },
    { name: 'بانوان', slug: 'womens-fitness', icon: 'PersonWoman1' },
    {
      name: 'ورزش بارداری و پس از زایمان',
      slug: 'prenatal-postnatal',
      icon: 'PersonPregnantWoman',
    },
    {
      name: 'ورزش افراد دارای معلولیت',
      slug: 'adaptive-fitness',
      icon: 'PersonWheelchair',
    },
    { name: 'آمادگی مسابقات بدنسازی', slug: 'contest-prep', icon: 'Trophy1' },
    {
      name: 'تغذیه ورزشی و سبک زندگی',
      slug: 'sports-nutrition',
      icon: 'Apple',
    },
  ]),
  [RefType.CANCELLATION_REASON]: withOrder([
    {
      name: 'تغییر برنامه شخصی',
      slug: 'schedule-change',
      icon: 'CalendarSlash1',
    },
    {
      name: 'بیماری یا آسیب‌دیدگی',
      slug: 'illness-or-injury',
      icon: 'PersonInjured',
    },
    { name: 'مشکل رفت‌وآمد', slug: 'transportation', icon: 'Car1' },
    { name: 'شرایط نامساعد جوی', slug: 'weather' },
    { name: 'رزرو اشتباه', slug: 'booking-mistake' },
    { name: 'یافتن گزینه مناسب‌تر', slug: 'found-another-option' },
    { name: 'لغو توسط باشگاه یا مربی', slug: 'provider-cancelled' },
    { name: 'سایر', slug: 'other' },
  ]),
  [RefType.DOCUMENT_TYPE]: withOrder([
    { name: 'کارت ملی', slug: 'national-id' },
    { name: 'مجوز فعالیت باشگاه', slug: 'club-license' },
    { name: 'مدرک مربیگری', slug: 'coaching-certificate', icon: 'AcademicCap' },
    { name: 'مدرک تخصصی', slug: 'specialty-certificate', icon: 'AcademicCap' },
    {
      name: 'گواهی کمک‌های اولیه',
      slug: 'first-aid-certificate',
      icon: 'HeartWellness1',
    },
    { name: 'بیمه مسئولیت', slug: 'liability-insurance', icon: 'ShieldCheck' },
    { name: 'اجاره‌نامه یا سند محل', slug: 'property-document' },
    { name: 'تصویر کارت بانکی', slug: 'bank-card' },
    { name: 'سایر مدرک', slug: 'other' },
  ]),
  [RefType.MEASUREMENT_UNIT]: withOrder([
    { name: 'تکرار', slug: 'rep' },
    { name: 'ست', slug: 'set' },
    { name: 'ثانیه', slug: 'second', icon: 'Clock' },
    { name: 'دقیقه', slug: 'minute', icon: 'Clock' },
    { name: 'ساعت', slug: 'hour', icon: 'Clock' },
    { name: 'متر', slug: 'meter' },
    { name: 'کیلومتر', slug: 'kilometer' },
    { name: 'سانتی‌متر', slug: 'centimeter' },
    { name: 'کیلوگرم', slug: 'kilogram', icon: 'Weight' },
    { name: 'گرم', slug: 'gram', icon: 'Weight' },
    { name: 'پوند', slug: 'pound', icon: 'Weight' },
    { name: 'کیلوکالری', slug: 'kilocalorie' },
    { name: 'میلی‌لیتر', slug: 'milliliter' },
    { name: 'لیتر', slug: 'liter' },
    { name: 'درصد', slug: 'percent' },
    { name: 'امتیاز', slug: 'point', icon: 'Trophy1' },
  ]),
};
