export const athleteMembershipsScreenStyles = {
  root: "bg-background",
  content: "flex flex-col gap-6 pb-10 pt-1",
  intro: "flex flex-col gap-2",
  introTitle: "tracking-tight text-foreground",
  introSubtitle: "text-muted",
  sectionTitle: "px-1 text-muted",
  section: "flex flex-col gap-2",
  heroList: "flex flex-col gap-4",
  heroCard:
    "flex flex-col gap-4 rounded-[24px] border-0 bg-surface p-5",
  heroHeader: "flex items-start justify-between gap-3",
  heroTitles: "flex min-w-0 flex-col gap-0.5",
  heroPlan: "text-foreground",
  heroClub: "text-muted",
  progressBlock: "flex flex-col gap-2",
  progressMeta: "flex items-center justify-between gap-3",
  progressLabel: "text-muted",
  progressTrack: "h-2.5 w-full overflow-hidden rounded-full bg-default",
  progressFill: "h-full rounded-full bg-accent",
  heroFooter: "flex items-center justify-between gap-3",
  expires: "text-muted",
  price: "text-foreground",
  pastList: "flex flex-col gap-3",
  pastCard:
    "flex flex-col gap-3 rounded-[24px] border-0 bg-surface p-4 opacity-80",
  pastHeader: "flex items-start justify-between gap-3",
  pastTitles: "flex min-w-0 flex-col gap-0.5",
  pastPlan: "text-foreground",
  pastMeta: "text-muted",
  empty:
    "flex flex-col items-center gap-2 rounded-[24px] border-0 bg-surface px-6 py-10 text-center",
  emptyTitle: "text-foreground",
  emptyBody: "text-muted",
} as const;
