export const coachSlotsManageScreenStyles = {
  root: "bg-background",
  content: "flex flex-col gap-6 pb-10 pt-1",
  intro: "flex flex-col gap-2",
  introTitle: "tracking-tight text-foreground",
  introSubtitle: "text-muted",
  weekRow: "flex items-center justify-between gap-3",
  weekLabel: "text-foreground",
  weekNav: "flex items-center gap-2",
  weekButton: "size-10 min-w-10 rounded-full bg-default p-0",
  weekButtonIcon: "text-foreground",
  days: "flex flex-col gap-5",
  day: "flex flex-col gap-2.5",
  dayLabel: "text-foreground",
  slotsRow: "flex flex-wrap gap-2",
  slotChip:
    "flex items-center gap-2 rounded-full border px-3.5 py-2 text-sm font-medium",
  slotOpen: "border-border bg-surface text-foreground",
  slotBooked: "border-success/40 bg-success/10 text-success",
  slotBlocked: "border-border bg-default text-muted",
  slotRemove: "text-muted transition-colors hover:text-danger",
  emptyDay: "text-muted",
  form: "flex flex-col gap-4 rounded-[24px] border-0 bg-surface p-5 shadow-sm shadow-foreground/5",
  formTitle: "text-foreground",
  formHint: "text-muted",
  fieldLabel: "px-1 text-muted",
  fieldGroup: "flex flex-col gap-2",
  errorText: "text-danger",
  loading: "flex min-h-[50vh] items-center justify-center",
} as const;
