import { Logo } from "@repo/ui/common/Logo";
import { getTranslations } from "next-intl/server";
import { BiometricAuthButton } from "@/shared/components/biometric-auth-button";
import { ThemeDemo } from "./theme-demo";

export default async function Home() {
  const t = await getTranslations("HomePage");

  return (
    <main className="mx-auto flex min-h-full w-full max-w-3xl flex-col gap-10 px-screen pt-[max(4rem,env(safe-area-inset-top))] pb-[max(4rem,env(safe-area-inset-bottom))]">
      <header className="flex flex-col gap-3">
        <div className="flex items-center gap-3">
          <Logo size="lg" gradient={false} />
          <p className="text-lg font-semibold tracking-tight text-foreground">
            {t("brand")}
          </p>
        </div>
        <h1 className="text-4xl font-semibold tracking-tight text-foreground">
          {t("title")}
        </h1>
        <p className="max-w-xl text-base text-muted">{t("description")}</p>
      </header>

      <section className="flex flex-col gap-3">
        <h2 className="text-lg font-medium text-foreground">
          {t("biometricLabel")}
        </h2>
        <BiometricAuthButton
          labels={{
            action: t("biometricAction"),
            reason: t("biometricReason"),
            cancel: t("biometricCancel"),
            androidTitle: t("biometricAndroidTitle"),
            androidSubtitle: t("biometricAndroidSubtitle"),
            success: t("biometricSuccess"),
            unavailable: t("biometricUnavailable"),
            failed: t("biometricFailed"),
          }}
        />
      </section>

      <ThemeDemo
        labels={{
          primaryAction: t("primaryAction"),
          secondaryAction: t("secondaryAction"),
          tertiaryAction: t("tertiaryAction"),
          dangerAction: t("dangerAction"),
          variantsLabel: t("variantsLabel"),
          surfacesLabel: t("surfacesLabel"),
          chipsLabel: t("chipsLabel"),
          iconsLabel: t("iconsLabel"),
          themeLabel: t("themeLabel"),
          chipNew: t("chipNew"),
          chipSuccess: t("chipSuccess"),
          chipDanger: t("chipDanger"),
          surfacePrimary: t("surfacePrimary"),
          surfaceSecondary: t("surfaceSecondary"),
          surfaceTertiary: t("surfaceTertiary"),
          callToActionLabel: t("callToActionLabel"),
          callToActionSubtitle: t("callToActionSubtitle"),
          callToActionTitle: t("callToActionTitle"),
          callToActionAction: t("callToActionAction"),
          callToActionPlus: t("callToActionPlus"),
          callToActionIcon: t("callToActionIcon"),
          callToActionOutlined: t("callToActionOutlined"),
          callToActionSoft: t("callToActionSoft"),
          callToActionMeta: t("callToActionMeta"),
          callToActionBadge: t("callToActionBadge"),
          socialMediaCardLabel: t("socialMediaCardLabel"),
          socialMediaCardTitle: t("socialMediaCardTitle"),
          socialMediaCardFacebook: t("socialMediaCardFacebook"),
          socialMediaCardInstagram: t("socialMediaCardInstagram"),
          socialMediaCardLinkedIn: t("socialMediaCardLinkedIn"),
          ibanCardLabel: t("ibanCardLabel"),
          ibanCardHolder: t("ibanCardHolder"),
          ibanCardExpiry: t("ibanCardExpiry"),
          ibanCardNumber: t("ibanCardNumber"),
          ticketCardLabel: t("ticketCardLabel"),
          ticketCardTitle: t("ticketCardTitle"),
          ticketCardSubtitle: t("ticketCardSubtitle"),
          clubSubscriptionCardLabel: t("clubSubscriptionCardLabel"),
          clubSubscriptionPlanName: t("clubSubscriptionPlanName"),
          clubSubscriptionPrice: t("clubSubscriptionPrice"),
          clubSubscriptionPriceSuffix: t("clubSubscriptionPriceSuffix"),
          clubSubscriptionDescription: t("clubSubscriptionDescription"),
          clubSubscriptionBadge: t("clubSubscriptionBadge"),
          clubSubscriptionAction: t("clubSubscriptionAction"),
          clubCancellationPolicyLabel: t("clubCancellationPolicyLabel"),
          clubCancellationStep1Title: t("clubCancellationStep1Title"),
          clubCancellationStep1Description: t(
            "clubCancellationStep1Description",
          ),
          clubCancellationStep2Title: t("clubCancellationStep2Title"),
          clubCancellationStep2Description: t(
            "clubCancellationStep2Description",
          ),
          clubCancellationStep3Title: t("clubCancellationStep3Title"),
          clubCancellationStep3Description: t(
            "clubCancellationStep3Description",
          ),
          clubCancellationStep4Title: t("clubCancellationStep4Title"),
          clubCancellationStep4Description: t(
            "clubCancellationStep4Description",
          ),
          coachName: t("coachName"),
          coachSpecialty: t("coachSpecialty"),
          coachCertified: t("coachCertified"),
          coachYears: t("coachYears"),
          coachMatchCardLabel: t("coachMatchCardLabel"),
          coachMatchCardTitle: t("coachMatchCardTitle"),
          coachMatchCardAction: t("coachMatchCardAction"),
          coachExpertCardLabel: t("coachExpertCardLabel"),
          coachFeatureCardLabel: t("coachFeatureCardLabel"),
          coachFeatureNew: t("coachFeatureNew"),
          coachFeatureClose: t("coachFeatureClose"),
          coachMapCardLabel: t("coachMapCardLabel"),
          coachMapAddress: t("coachMapAddress"),
          coachMapGetDirections: t("coachMapGetDirections"),
          coachMapViewDetails: t("coachMapViewDetails"),
          coachNearbyCardLabel: t("coachNearbyCardLabel"),
          coachNearbyPrice: t("coachNearbyPrice"),
          coachNearbyDistance: t("coachNearbyDistance"),
          coachNearbyRemote: t("coachNearbyRemote"),
          coachPopularItemLabel: t("coachPopularItemLabel"),
          coachVerified: t("coachVerified"),
          metricPromoCardLabel: t("metricPromoCardLabel"),
          metricPromoTitle: t("metricPromoTitle"),
          metricPromoAction: t("metricPromoAction"),
          metricPromoImageAlt: t("metricPromoImageAlt"),
          metricReorderItemLabel: t("metricReorderItemLabel"),
          metricReorderTitle: t("metricReorderTitle"),
          metricReorderRemove: t("metricReorderRemove"),
          metricReorderDrag: t("metricReorderDrag"),
          muscleCardLabel: t("muscleCardLabel"),
          muscleCardAbs: t("muscleCardAbs"),
          muscleCardLowerLeg: t("muscleCardLowerLeg"),
          reviewCardLabel: t("reviewCardLabel"),
          reviewCardTitle: t("reviewCardTitle"),
          reviewCardContent: t("reviewCardContent"),
          reviewCardDate: t("reviewCardDate"),
          reviewCardVerified: t("reviewCardVerified"),
          reviewCardLike: t("reviewCardLike"),
          reviewCardDislike: t("reviewCardDislike"),
          reviewCardReport: t("reviewCardReport"),
          scheduleWorkoutCardLabel: t("scheduleWorkoutCardLabel"),
          scheduleWorkoutIntensity: t("scheduleWorkoutIntensity"),
          sportCardLabel: t("sportCardLabel"),
          sportCardSubtitle: t("sportCardSubtitle"),
          sportCardTitle: t("sportCardTitle"),
          sportCardAction: t("sportCardAction"),
          sportCategoryCardLabel: t("sportCategoryCardLabel"),
          sportCategoryCardSubtitle: t("sportCategoryCardSubtitle"),
          sportCategoryCardTitle: t("sportCategoryCardTitle"),
          sportCategoryCardAction: t("sportCategoryCardAction"),
          clubCardLabel: t("clubCardLabel"),
          clubCardTitle: t("clubCardTitle"),
          clubCardSubtitle: t("clubCardSubtitle"),
          clubCardPricePrefix: t("clubCardPricePrefix"),
          clubCardPrice: t("clubCardPrice"),
          clubCardPriceSuffix: t("clubCardPriceSuffix"),
          clubCardAction: t("clubCardAction"),
          clubCardShare: t("clubCardShare"),
          clubCardFavorite: t("clubCardFavorite"),
          clubCardFeatureUpgrade: t("clubCardFeatureUpgrade"),
          clubCardFeatureDining: t("clubCardFeatureDining"),
          clubCardFeatureWifi: t("clubCardFeatureWifi"),
          clubBranchCardLabel: t("clubBranchCardLabel"),
          clubBranchCardTitle: t("clubBranchCardTitle"),
          clubBranchCardSubtitle: t("clubBranchCardSubtitle"),
          clubBranchCardAction: t("clubBranchCardAction"),
          cityCardLabel: t("cityCardLabel"),
          cityCardCity: t("cityCardCity"),
          cityCardTitle: t("cityCardTitle"),
          cityCardDiscount: t("cityCardDiscount"),
          cityCardAction: t("cityCardAction"),
          districtCardLabel: t("districtCardLabel"),
          districtCardTitle: t("districtCardTitle"),
          districtCardSubtitle: t("districtCardSubtitle"),
          districtCardAction: t("districtCardAction"),
          clubEquipmentCardLabel: t("clubEquipmentCardLabel"),
          clubEquipmentCardTitle: t("clubEquipmentCardTitle"),
          clubEquipmentCardSubtitle: t("clubEquipmentCardSubtitle"),
          clubEquipmentCardMeta: t("clubEquipmentCardMeta"),
          achievementCardLabel: t("achievementCardLabel"),
          achievementCardAria: t("achievementCardAria"),
          clubAmenityCardLabel: t("clubAmenityCardLabel"),
          clubAmenityCardTitle: t("clubAmenityCardTitle"),
          clubAmenityCardSubtitle: t("clubAmenityCardSubtitle"),
          clubClassCardLabel: t("clubClassCardLabel"),
          clubClassCardCategory: t("clubClassCardCategory"),
          clubClassCardDate: t("clubClassCardDate"),
          clubClassCardTitle: t("clubClassCardTitle"),
          clubClassCardAuthor: t("clubClassCardAuthor"),
          clubClassCardDuration: t("clubClassCardDuration"),
          clubClassCardAction: t("clubClassCardAction"),
          workoutCardLabel: t("workoutCardLabel"),
          workoutCardCategory: t("workoutCardCategory"),
          workoutCardTitle: t("workoutCardTitle"),
          workoutCardSets: t("workoutCardSets"),
          workoutCardDuration: t("workoutCardDuration"),
          workoutCardPlay: t("workoutCardPlay"),
          clubLocationCardLabel: t("clubLocationCardLabel"),
          clubLocationCardOpen: t("clubLocationCardOpen"),
          clubLocationCardHours: t("clubLocationCardHours"),
          clubLocationCardDistanceValue: t("clubLocationCardDistanceValue"),
          clubLocationCardDistance: t("clubLocationCardDistance"),
          clubLocationCardScoreValue: t("clubLocationCardScoreValue"),
          clubLocationCardScore: t("clubLocationCardScore"),
          clubLocationCardStudentsValue: t("clubLocationCardStudentsValue"),
          clubLocationCardStudents: t("clubLocationCardStudents"),
          knobSliderLabel: t("knobSliderLabel"),
          fractionalPickerLabel: t("fractionalPickerLabel"),
          weightSliderLabel: t("weightSliderLabel"),
          inputOTPLabel: t("inputOTPLabel"),
          inputOTPFilled: t("inputOTPFilled"),
          inputOTPError: t("inputOTPError"),
          swipeButtonLabel: t("swipeButtonLabel"),
          swipeButtonAction: t("swipeButtonAction"),
          swipeButtonConfirm: t("swipeButtonConfirm"),
          swipeButtonContinue: t("swipeButtonContinue"),
          swipeButtonSave: t("swipeButtonSave"),
          swipeButtonDelete: t("swipeButtonDelete"),
          uploaderDemoLabel: t("uploaderDemoLabel"),
          uploaderLabel: t("uploaderLabel"),
          fileItemLabel: t("fileItemLabel"),
          fileItemTypeLabel: t("fileItemTypeLabel"),
          uploaderDemoFileName: t("uploaderDemoFileName"),
          uploaderDemoFileSize: t("uploaderDemoFileSize"),
          uploaderDemoSuccess: t("uploaderDemoSuccess"),
          uploaderDemoError: t("uploaderDemoError"),
          uploaderDemoRetry: t("uploaderDemoRetry"),
          statsCardLabel: t("statsCardLabel"),
          statsCardHydrationTitle: t("statsCardHydrationTitle"),
          statsCardHydrationUnit: t("statsCardHydrationUnit"),
          statsCardScoreTitle: t("statsCardScoreTitle"),
          statsCardScoreUnit: t("statsCardScoreUnit"),
          metricCardLabel: t("metricCardLabel"),
          metricCardPeriod: t("metricCardPeriod"),
          metricCardHeartRateTitle: t("metricCardHeartRateTitle"),
          metricCardHeartRateStatus: t("metricCardHeartRateStatus"),
          metricCardHeartRateUnit: t("metricCardHeartRateUnit"),
          metricCardHeartRateValue: t("metricCardHeartRateValue"),
          metricCardWeightTitle: t("metricCardWeightTitle"),
          metricCardWeightStatus: t("metricCardWeightStatus"),
          metricCardWeightUnit: t("metricCardWeightUnit"),
          metricCardWeightValue: t("metricCardWeightValue"),
          metricCardHydrationTitle: t("metricCardHydrationTitle"),
          metricCardHydrationStatus: t("metricCardHydrationStatus"),
          metricCardHydrationUnit: t("metricCardHydrationUnit"),
          metricCardHydrationValue: t("metricCardHydrationValue"),
          metricCardBloodPressureTitle: t("metricCardBloodPressureTitle"),
          metricCardBloodPressureStatus: t("metricCardBloodPressureStatus"),
          metricCardBloodPressureUnit: t("metricCardBloodPressureUnit"),
          metricCardBloodPressureValue: t("metricCardBloodPressureValue"),
          metricCardSleepTitle: t("metricCardSleepTitle"),
          metricCardSleepStatus: t("metricCardSleepStatus"),
          metricCardSleepUnit: t("metricCardSleepUnit"),
          metricCardSleepValue: t("metricCardSleepValue"),
          metricCardNutritionTitle: t("metricCardNutritionTitle"),
          metricCardNutritionStatus: t("metricCardNutritionStatus"),
          metricCardNutritionUnit: t("metricCardNutritionUnit"),
          metricCardNutritionValue: t("metricCardNutritionValue"),
          metricCardMoodTitle: t("metricCardMoodTitle"),
          metricCardMoodStatus: t("metricCardMoodStatus"),
          metricCardMoodValue: t("metricCardMoodValue"),
          metricCardStepsTitle: t("metricCardStepsTitle"),
          metricCardStepsStatus: t("metricCardStepsStatus"),
          metricCardStepsUnit: t("metricCardStepsUnit"),
          metricCardStepsValue: t("metricCardStepsValue"),
          metricGoalCardLabel: t("metricGoalCardLabel"),
          metricGoalValue: t("metricGoalValue"),
          metricGoalUnit: t("metricGoalUnit"),
          metricGoalDescription: t("metricGoalDescription"),
          metricGoalProgress: t("metricGoalProgress"),
          metricGoalCurrent: t("metricGoalCurrent"),
          metricGoalEdit: t("metricGoalEdit"),
          metricHistoryItemLabel: t("metricHistoryItemLabel"),
          metricHistoryValue: t("metricHistoryValue"),
          metricHistoryTime: t("metricHistoryTime"),
          metricHistorySubtitle: t("metricHistorySubtitle"),
          metricHistoryAlert: t("metricHistoryAlert"),
          metricInsightCardLabel: t("metricInsightCardLabel"),
          metricInsightLabel: t("metricInsightLabel"),
          metricInsightValue: t("metricInsightValue"),
          metricInsightChange: t("metricInsightChange"),
          metricInsightTip: t("metricInsightTip"),
          areaLineChartLabel: t("areaLineChartLabel"),
          headerLabel: t("headerLabel"),
          headerTitle: t("headerTitle"),
          headerBack: t("headerBack"),
          headerAction: t("headerAction"),
          logoMarkLabel: t("logoMarkLabel"),
          adaptiveSliderLabel: t("adaptiveSliderLabel"),
          adaptiveSliderValueLabel: t("adaptiveSliderValueLabel"),
          adaptiveSliderUnit: t("adaptiveSliderUnit"),
          screensLabel: t("screensLabel"),
          screensAppLabel: t("screensAppLabel"),
          screensDiscoveryLabel: t("screensDiscoveryLabel"),
          screensAthleteLabel: t("screensAthleteLabel"),
          screensCoachLabel: t("screensCoachLabel"),
          screensOwnerLabel: t("screensOwnerLabel"),
          screenSplash: t("screenSplash"),
          screenAthleteHome: t("screenAthleteHome"),
          screenCoachHome: t("screenCoachHome"),
          screenOwnerHome: t("screenOwnerHome"),
          screenOwnerClubsCreate: t("screenOwnerClubsCreate"),
          screenHome: t("screenHome"),
          screenDiscoveryMap: t("screenDiscoveryMap"),
          screenDiscoveryCoaches: t("screenDiscoveryCoaches"),
          screenDiscoveryClubs: t("screenDiscoveryClubs"),
          screenCoachDetail: t("screenCoachDetail"),
          screenClubDetail: t("screenClubDetail"),
          screenClubReviews: t("screenClubReviews"),
          screenClubBranches: t("screenClubBranches"),
          screenClubSports: t("screenClubSports"),
          screenClubClasses: t("screenClubClasses"),
          screenClubClassDetail: t("screenClubClassDetail"),
          screenFitnessMetrics: t("screenFitnessMetrics"),
          screenFitnessMetricsReorder: t("screenFitnessMetricsReorder"),
          screenWeightMetrics: t("screenWeightMetrics"),
          screenWeightHistory: t("screenWeightHistory"),
          screenWeightDetail: t("screenWeightDetail"),
          screenCoachCalendarDaily: t("screenCoachCalendarDaily"),
          screenCoachCalendarWeekly: t("screenCoachCalendarWeekly"),
          componentsNavLabel: t("componentsNavLabel"),
          profileHeaderLabel: t("profileHeaderLabel"),
          profileHeaderHint: t("profileHeaderHint"),
          quickActionCardLabel: t("quickActionCardLabel"),
          quickActionCardClasses: t("quickActionCardClasses"),
          quickActionCardBookings: t("quickActionCardBookings"),
          quickActionCardEquipment: t("quickActionCardEquipment"),
          quickActionCardMore: t("quickActionCardMore"),
          bottomNavLabel: t("bottomNavLabel"),
          bottomNavPreview: t("bottomNavPreview"),
          bottomNavHome: t("bottomNavHome"),
          bottomNavAnalytics: t("bottomNavAnalytics"),
          bottomNavResources: t("bottomNavResources"),
          bottomNavProfile: t("bottomNavProfile"),
          bottomNavCreate: t("bottomNavCreate"),
          bottomNavAria: t("bottomNavAria"),
          bottomNavActionsLabel: t("bottomNavActionsLabel"),
          bottomNavRoleAthlete: t("bottomNavRoleAthlete"),
          bottomNavRoleCoach: t("bottomNavRoleCoach"),
          bottomNavRoleOwner: t("bottomNavRoleOwner"),
          bottomNavHealthMetrics: t("bottomNavHealthMetrics"),
          bottomNavActivity: t("bottomNavActivity"),
          bottomNavSleep: t("bottomNavSleep"),
          bottomNavNutrition: t("bottomNavNutrition"),
          bottomNavWorkouts: t("bottomNavWorkouts"),
          bottomNavCoachBooking: t("bottomNavCoachBooking"),
          bottomNavCommunity: t("bottomNavCommunity"),
          bottomNavClients: t("bottomNavClients"),
          bottomNavSchedule: t("bottomNavSchedule"),
          bottomNavPrograms: t("bottomNavPrograms"),
          bottomNavMessages: t("bottomNavMessages"),
          bottomNavClubs: t("bottomNavClubs"),
          bottomNavStaff: t("bottomNavStaff"),
          bottomNavClasses: t("bottomNavClasses"),
          bottomNavEquipment: t("bottomNavEquipment"),
          bottomNavBookings: t("bottomNavBookings"),
          bottomNavMarketing: t("bottomNavMarketing"),
        }}
      />
    </main>
  );
}
