export const discoveryClubsReserveScreenStyles = {
  root: "relative min-h-dvh w-full bg-background",
  scroll: [
    "flex min-h-dvh flex-col",
    "pb-[calc(6.5rem+env(safe-area-inset-bottom))]",
  ].join(" "),
  hero: "relative h-[36dvh] min-h-56 w-full overflow-hidden",
  heroImage: "object-cover object-center",
  heroScrim: [
    "pointer-events-none absolute inset-0",
    "bg-linear-to-t from-background via-background/45 to-background/15",
  ].join(" "),
  sheet: [
    "relative z-10 -mt-14 flex flex-col gap-6",
    "rounded-t-[2.5rem] bg-background px-5 pb-6 pt-7",
  ].join(" "),
  titleBlock: "flex flex-col gap-1.5",
  eyebrow: "text-sm font-medium text-muted",
  title:
    "text-balance text-[1.65rem] leading-tight tracking-tight text-foreground",
  location: "text-sm text-muted",
  stepPanel: "flex flex-col gap-6",
  section: "flex flex-col gap-3",
  sectionHeader: "flex items-center justify-between gap-3",
  sectionTitle: "text-foreground",
  sectionHint: "text-muted",
  days: [
    "-mx-5 flex snap-x snap-mandatory gap-2.5 overflow-x-auto px-5 pb-1",
    "[-ms-overflow-style:none] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden",
  ].join(" "),
  slotsGrid: "grid grid-cols-1 gap-2.5",
  slot: [
    "flex h-auto w-full flex-row items-center gap-3",
    "rounded-[1.25rem] border-0 bg-surface px-3.5 py-3.5 text-start shadow-sm shadow-foreground/5",
    "transition-[border-color,background-color,box-shadow]",
    "[--button-bg:var(--surface)]",
    "[--button-bg-hover:color-mix(in_oklab,var(--accent)_8%,var(--surface))]",
    "[--button-bg-pressed:color-mix(in_oklab,var(--accent)_12%,var(--surface))]",
  ].join(" "),
  slotSelected: [
    "border-accent",
    "bg-[color-mix(in_oklab,var(--accent)_12%,var(--surface))]",
    "ring-2 ring-accent/20",
    "[--button-bg:color-mix(in_oklab,var(--accent)_12%,var(--surface))]",
    "[--button-bg-hover:color-mix(in_oklab,var(--accent)_16%,var(--surface))]",
    "[--button-bg-pressed:color-mix(in_oklab,var(--accent)_18%,var(--surface))]",
  ].join(" "),
  slotDisabled: "opacity-55",
  slotIconWrap: [
    "flex size-11 shrink-0 items-center justify-center rounded-full",
    "bg-default text-accent",
  ].join(" "),
  slotIconWrapSelected: "bg-accent text-accent-foreground",
  slotBody: "flex min-w-0 flex-1 flex-col items-start gap-1",
  slotTime: "text-foreground",
  slotCapacity: "text-muted",
  slotCapacityLow: "text-warning",
  slotCapacityFull: "text-danger",
  slotCheck: "shrink-0 text-accent",
  empty: [
    "flex w-full flex-col items-center gap-2 rounded-2xl border border-border/60",
    "bg-surface px-6 py-10 text-center",
  ].join(" "),
  emptyBody: "text-muted",
  plans: "flex flex-col gap-3",
  planCard: [
    "h-auto w-full flex-col items-start gap-2 rounded-2xl border border-border/60",
    "bg-surface p-4 text-start font-normal transition-[border-color,background-color,box-shadow]",
    "[--button-bg:var(--surface)]",
    "[--button-bg-hover:color-mix(in_oklab,var(--accent)_8%,var(--surface))]",
    "[--button-bg-pressed:color-mix(in_oklab,var(--accent)_12%,var(--surface))]",
  ].join(" "),
  planCardSelected: [
    "border-accent",
    "bg-[color-mix(in_oklab,var(--accent)_12%,var(--surface))]",
    "ring-2 ring-accent/20",
    "[--button-bg:color-mix(in_oklab,var(--accent)_12%,var(--surface))]",
    "[--button-bg-hover:color-mix(in_oklab,var(--accent)_16%,var(--surface))]",
    "[--button-bg-pressed:color-mix(in_oklab,var(--accent)_18%,var(--surface))]",
  ].join(" "),
  planHeader: "flex w-full items-start justify-between gap-3",
  planTitleBlock: "flex min-w-0 flex-col gap-1",
  planTitle: "text-foreground",
  planPriceRow: "flex flex-wrap items-baseline gap-1 text-accent",
  planPrice: "text-lg font-semibold tabular-nums leading-none",
  planPriceSuffix: "text-xs font-normal text-muted",
  planDescription: "text-start text-muted",
  planCheck: "mt-0.5 shrink-0 text-accent",
  summaryCard: [
    "flex flex-col gap-0 overflow-hidden rounded-2xl border border-border/60",
    "bg-surface",
  ].join(" "),
  summaryRow: [
    "flex items-center justify-between gap-3 px-4 py-3.5",
    "border-b border-border/50 last:border-b-0",
  ].join(" "),
  summaryLabel: "text-muted",
  summaryValue: "text-end text-foreground",
  summaryTotalRow: "bg-default/40",
  summaryTotalValue: "text-end text-foreground",
  footerRow: "items-center justify-between gap-4",
  priceGroup: "flex min-w-0 flex-col gap-1",
  priceLabel: "text-muted",
  priceRow: "flex min-w-0 flex-wrap items-baseline gap-1 text-foreground",
  pricePrefix: "text-xs font-normal text-muted",
  price: [
    "inline-block text-xl font-semibold leading-none text-foreground",
    "[font-variant-numeric:tabular-nums]",
  ].join(" "),
  priceSuffix: "text-xs font-normal text-muted",
  confirm: "min-w-0 h-14 w-1/2",
  confirmLabel: "truncate text-background",
  confirmIcon: "shrink-0 text-background",
} as const;
