export const discoveryClubsReserveScreenStyles = {
  root: "bg-background",
  content: "flex flex-col gap-6 pb-10 pt-1",
  intro: "flex flex-col gap-2",
  introTitle: "tracking-tight text-foreground",
  introSubtitle: "text-muted",
  sectionTitle: "px-1 text-muted",
  section: "flex flex-col gap-2",
  days: "-mx-screen flex snap-x snap-mandatory gap-2.5 overflow-x-auto px-screen pb-1 [-ms-overflow-style:none] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden",
  dayChip:
    "flex h-auto shrink-0 snap-start flex-col items-center gap-0.5 rounded-[18px] px-4 py-3",
  dayWeekday: "text-sm font-semibold",
  dayDate: "text-xs",
  slotsGrid: "grid grid-cols-2 gap-3",
  slot: "flex h-auto flex-col items-start gap-1 rounded-[18px] border border-border bg-surface p-4 text-start",
  slotSelected: "border-accent bg-accent/10",
  slotTime: "text-foreground",
  slotCapacity: "text-muted",
  slotCapacityLow: "text-warning",
  slotCapacityFull: "text-danger",
  planCard:
    "h-auto w-full flex-col items-start gap-1.5 rounded-[24px] border border-border bg-surface p-4 text-start font-normal",
  planCardSelected: "border-accent bg-accent/10",
  planHeader: "flex w-full items-center justify-between gap-3",
  planTitle: "text-foreground",
  planPrice: "text-accent",
  planDescription: "text-muted",
  plans: "flex flex-col gap-3",
  summaryCard:
    "flex flex-col gap-3 rounded-[24px] border border-border bg-surface p-5",
  summaryRow: "flex items-center justify-between gap-3",
  summaryLabel: "text-muted",
  summaryValue: "text-foreground text-end",
  summaryDivider: "h-px bg-border",
  summaryTotalValue: "text-foreground",
  empty:
    "col-span-2 flex flex-col items-center gap-2 rounded-[24px] border border-border bg-surface px-6 py-10 text-center",
  emptyBody: "text-muted",
  navRow: "flex gap-3 pt-1",
  navBack: "flex-1",
  navNext: "flex-[2]",
} as const;
