export const discoveryCoachesDetailBodySectionStyles = {
  root: "flex flex-col gap-7",
  section: "flex flex-col gap-3",
  sectionHeader: "flex items-center justify-between gap-3",
  sectionTitle: "min-w-0 flex-1 text-foreground",
  seeAll: "text-sm font-semibold text-accent",
  statsBar: [
    "flex w-full items-stretch overflow-hidden rounded-[1.75rem]",
    "border border-border/70 bg-default",
  ].join(" "),
  statCell: [
    "relative flex min-w-0 flex-1 flex-col items-center justify-center gap-2",
    "px-2 py-5",
    "after:absolute after:end-0 after:top-[18%] after:bottom-[18%] after:w-px after:bg-border",
    "last:after:hidden",
  ].join(" "),
  statValue: "text-[1.65rem] leading-none tracking-tight text-foreground",
  statMeta: "flex items-center gap-1.5 text-muted",
  statIcon: "shrink-0",
  statIconMuted: "text-muted",
  statIconScore: "text-warning",
  statIconAccent: "text-accent",
  statLabel: "text-[0.8rem] leading-none text-muted",
  bodyText: "text-sm leading-relaxed text-muted",
  descriptionWrap: "relative",
  descriptionClamped: "line-clamp-3",
  seeMoreFade: [
    "pointer-events-none absolute inset-x-0 bottom-0 z-10",
    "flex items-end justify-center pb-0.5 pt-10",
    "bg-linear-to-t from-background via-background/90 to-transparent",
  ].join(" "),
  seeMoreTrigger: "pointer-events-auto text-accent",
  seeLess: "mt-2 flex self-start",
  chips: "flex flex-wrap gap-2",
  chip: [
    "h-10 rounded-full border border-border bg-transparent px-3.5",
    "[--chip-bg:transparent] [--chip-fg:var(--foreground)]",
    "[&_.chip__label]:text-sm [&_.chip__label]:font-medium",
  ].join(" "),
  chipIcon: "shrink-0 text-muted",
  gallery: [
    "flex gap-2.5 overflow-x-auto pb-1",
    "[-ms-overflow-style:none] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden",
  ].join(" "),
  galleryItem:
    "relative h-24 w-28 shrink-0 overflow-hidden rounded-2xl bg-default",
  galleryImage: "object-cover",
  slotGroup: "flex flex-col gap-3 rounded-[1.5rem] border border-border/70 bg-surface p-4",
  slotDay: "flex flex-col gap-2",
  slotDayLabel: "text-sm font-semibold text-foreground",
  slotRow: "flex flex-wrap gap-2",
  slotChip: "min-w-[4.5rem] rounded-xl border border-border px-3 py-2 text-sm",
  slotAvailable: "border-accent/50 text-accent",
  slotSelected: "border-transparent bg-accent text-accent-foreground",
  slotUnavailable: "border-border text-muted opacity-60",
  subscriptionGroup: "flex w-full flex-col gap-4",
  subscriptionRadio: [
    "w-full overflow-visible border-0 bg-transparent p-0 shadow-none",
    "data-[selected=true]:bg-transparent",
  ].join(" "),
  subscriptionContent: [
    "group w-full gap-0 bg-transparent p-0 shadow-none",
    "hover:bg-transparent data-[hovered=true]:bg-transparent",
    "data-[selected=true]:bg-transparent data-[selected=true]:data-[hovered=true]:bg-transparent",
    "pressed:bg-transparent data-[pressed=true]:bg-transparent",
  ].join(" "),
  subscriptionControl: [
    "flex size-8 shrink-0 items-center justify-center rounded-full border-2 border-accent",
    "bg-transparent text-accent-foreground shadow-none",
    "group-data-[selected=true]:border-transparent group-data-[selected=true]:bg-accent",
    "group-data-[selected=true]:text-accent-foreground",
    "group-data-[pressed=true]:scale-95",
  ].join(" "),
  subscriptionIndicator:
    "flex items-center justify-center text-current [&_svg]:size-[18px]",
  clubCard: "min-w-0",
  locationCard:
    "flex flex-col gap-2 rounded-[1.5rem] border border-border/70 bg-surface p-4",
  locationLink: "text-sm font-semibold text-accent",
  timeline: "relative flex flex-col gap-5 ps-1",
  timelineItem: "relative flex gap-3",
  timelineRail: [
    "absolute start-[0.55rem] top-3 bottom-[-1.25rem] w-px",
    "bg-accent/35",
  ].join(" "),
  timelineDot: [
    "relative z-10 mt-1.5 size-2.5 shrink-0 rounded-full",
    "bg-accent ring-4 ring-accent/15",
  ].join(" "),
  timelineBody: "min-w-0 flex-1",
  timelineTitle: "text-foreground",
  timelineText: "mt-1 leading-relaxed text-muted",
} as const;
