export const discoveryCoachesDetailBodySectionStyles = {
  root: "flex flex-col gap-8 px-5 pb-4 pt-4",
  section: "flex flex-col gap-3",
  sectionHeader: "flex items-center justify-between gap-3",
  sectionHeaderAside: "flex shrink-0 items-center gap-2",
  sectionTitleRow: "flex min-w-0 flex-1 items-center gap-2",
  sectionTitleIcon: "shrink-0 text-accent",
  sectionTitle: "min-w-0 flex-1 text-foreground",
  seeAll: "cursor-pointer text-sm font-medium text-accent no-underline",
  bodyText: "text-sm leading-relaxed text-muted",
  descriptionWrap: "relative",
  descriptionClamped: "line-clamp-3",
  seeMoreFade: [
    "pointer-events-none absolute inset-x-0 bottom-0 z-10",
    "flex items-end justify-center pb-0.5 pt-10",
    "bg-linear-to-t from-surface via-surface/90 to-transparent",
  ].join(" "),
  seeMoreTrigger: "pointer-events-auto",
  seeLess: "mt-2 flex self-start",
  statsBar: [
    "grid grid-cols-3 gap-2 rounded-[1.5rem] border border-border/60",
    "bg-default px-2 py-3",
  ].join(" "),
  statCell: "flex min-w-0 flex-col items-center gap-1 text-center",
  statValue: "text-[1.25rem] leading-none tracking-tight text-foreground",
  statMeta: "flex items-center gap-1 text-muted",
  statIcon: "shrink-0",
  statIconMuted: "text-muted",
  statIconScore: "text-warning",
  statIconAccent: "text-accent",
  statLabel: "text-[0.7rem]",
  carousel: [
    "min-w-0 -mx-5 w-[calc(100%+2.5rem)] max-w-none overflow-hidden",
    "[-ms-overflow-style:none] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden pe-[calc(env(safe-area-inset-right)+1rem)]",
  ].join(" "),
  carouselTrack: "flex touch-pan-y gap-3 px-5 pb-1",
  slide: "min-w-0 shrink-0",
  amenitySlide: "min-w-0 shrink-0",
  amenityCard: "min-w-[17.5rem] border border-border/60 bg-default shadow-none",
  branchSlide: "min-w-0 shrink-0",
  coachSlide: "w-[min(16.5rem,calc(100vw-4.5rem))] min-w-0 shrink-0",
  coachCard: "w-full",
  reviewSlide: "w-[min(20rem,calc(100vw-3.5rem))] min-w-0 shrink-0",
  reviewCard: "h-full",
} as const;
