export const ownerFinanceScreenStyles = {
  root: "bg-background",
  content: "flex flex-col gap-6 pb-10 pt-1",
  intro: "flex flex-col gap-2",
  introTitle: "tracking-tight text-foreground",
  introSubtitle: "text-muted",
  hero:
    "flex flex-col gap-2 rounded-[24px] border border-border bg-surface p-5",
  heroHeader: "flex items-center gap-2 text-muted",
  heroIcon: "shrink-0 text-accent",
  heroLabel: "text-muted",
  heroAmount: "text-foreground",
  heroHint: "text-muted",
  statsGrid: "grid grid-cols-2 gap-4",
  chartCard:
    "flex flex-col gap-3 rounded-[24px] border border-border bg-surface p-4",
  chartTitle: "text-foreground",
  chart: "w-full",
  section: "flex flex-col gap-3",
  sectionTitle: "text-foreground",
  sectionHint: "text-muted",
  groupCard: "overflow-hidden rounded-[24px] border border-border bg-surface",
  row: "flex w-full items-center gap-3 px-4 py-3.5",
  rowBody: "flex min-w-0 flex-1 flex-col gap-0.5",
  rowLabel: "text-foreground",
  rowHint: "text-muted",
  rowValue: "shrink-0 text-sm text-foreground",
  rowValueBold: "shrink-0 text-sm font-bold text-foreground",
  rowValueCredit: "shrink-0 text-sm font-medium text-success",
  rowValueDebit: "shrink-0 text-sm font-medium text-danger",
  totalRowLabel: "font-bold text-foreground",
  divider: "mx-4 h-px bg-border",
  totalDivider: "mx-4 h-px bg-border",
} as const;
