import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument, Types } from 'mongoose';
import {
  BannerAspectRatio,
  BannerLinkKind,
  BannerOverlayPlacement,
  BannerPlacement,
  BannerRadius,
  PublishStatus,
} from '../common/enums';
import { Media } from './media.schema';
import { User } from './user.schema';

export type BannerDocument = HydratedDocument<Banner>;

@Schema({ _id: false })
export class BannerSlideTitle {
  @Prop({ required: true, trim: true, maxlength: 120 })
  text!: string;

  @Prop({
    type: String,
    enum: BannerOverlayPlacement,
    default: BannerOverlayPlacement.BOTTOM_START,
  })
  placement!: BannerOverlayPlacement;
}

export const BannerSlideTitleSchema =
  SchemaFactory.createForClass(BannerSlideTitle);

@Schema({ _id: false })
export class BannerSlideAction {
  @Prop({ required: true, trim: true, maxlength: 80 })
  label!: string;

  @Prop({
    type: String,
    enum: BannerOverlayPlacement,
    default: BannerOverlayPlacement.BOTTOM_END,
  })
  placement!: BannerOverlayPlacement;
}

export const BannerSlideActionSchema =
  SchemaFactory.createForClass(BannerSlideAction);

@Schema({ _id: false })
export class BannerSlide {
  @Prop({ type: Types.ObjectId, ref: Media.name, required: true })
  mediaId!: Types.ObjectId;

  @Prop({
    type: String,
    enum: BannerLinkKind,
    default: BannerLinkKind.NONE,
  })
  linkKind!: BannerLinkKind;

  /** In-app route for `internal`, absolute URL for `external`. */
  @Prop({ trim: true, maxlength: 2000 })
  linkUrl?: string;

  @Prop({ trim: true, maxlength: 200 })
  alt?: string;

  /** Soft theme-aware scrim over the image for title/action readability. */
  @Prop({ default: false })
  gradient!: boolean;

  @Prop({ type: BannerSlideTitleSchema })
  title?: BannerSlideTitle;

  @Prop({ type: BannerSlideActionSchema })
  action?: BannerSlideAction;
}

export const BannerSlideSchema = SchemaFactory.createForClass(BannerSlide);

@Schema({ _id: false })
export class BannerSchedule {
  @Prop({ type: Date })
  startsAt?: Date;

  @Prop({ type: Date })
  endsAt?: Date;
}

export const BannerScheduleSchema =
  SchemaFactory.createForClass(BannerSchedule);

@Schema({ timestamps: true, collection: 'banners' })
export class Banner {
  /** Admin-facing label; never rendered to end users. */
  @Prop({ default: '', trim: true, maxlength: 200 })
  label!: string;

  /** Stable identifier generated by the system; unique within a placement. */
  @Prop({ trim: true, maxlength: 120 })
  slug?: string;

  @Prop({
    type: String,
    enum: BannerPlacement,
    required: true,
    index: true,
  })
  placement!: BannerPlacement;

  /** Shared frame ratio for every slide in this banner. */
  @Prop({
    type: String,
    enum: BannerAspectRatio,
    default: BannerAspectRatio.RATIO_16_9,
  })
  ratio!: BannerAspectRatio;

  /** Shared corner radius for every slide in this banner. */
  @Prop({
    type: String,
    enum: BannerRadius,
    default: BannerRadius.SURFACE,
  })
  radius!: BannerRadius;

  @Prop({ type: [BannerSlideSchema], default: [] })
  slides!: BannerSlide[];

  @Prop({
    type: String,
    enum: PublishStatus,
    default: PublishStatus.DRAFT,
    index: true,
  })
  publishStatus!: PublishStatus;

  /** Optional campaign window; open-ended when a bound is missing. */
  @Prop({ type: BannerScheduleSchema, default: () => ({}) })
  schedule!: BannerSchedule;

  /** Manual ordering within a placement (ascending). */
  @Prop({ default: 0 })
  order!: number;

  @Prop({ type: Types.ObjectId, ref: User.name })
  updatedBy?: Types.ObjectId;

  createdAt!: Date;
  updatedAt!: Date;
}

export const BannerSchema = SchemaFactory.createForClass(Banner);

BannerSchema.index({ placement: 1, publishStatus: 1, order: 1 });
BannerSchema.index(
  { placement: 1, slug: 1 },
  {
    unique: true,
    partialFilterExpression: { slug: { $exists: true, $type: 'string' } },
  },
);
