import { useCallback, useEffect, useMemo, useState } from "react";
import { adminAccessApi, adminV2Client, auditApi, commerceApi, financeApi, membershipsApi, notificationsApi, organizationsApi, supplyApi, verificationsApi } from "@/shared/lib/api";

export type AdminP0Domain = "dashboard" | "users" | "organizations" | "catalog" | "bookings" | "memberships" | "finance" | "verifications" | "notifications" | "audit";
type AdminRow = { id: string; title: string; detail: string; state: string; raw: Record<string, unknown> };
const titles: Record<AdminP0Domain, string> = { dashboard: "داشبورد آمادگی انتشار", users: "کاربران، نقش‌ها و دسترسی‌ها", organizations: "سازمان‌ها، باشگاه‌ها و شعب", catalog: "منابع و خدمات قابل رزرو", bookings: "رزروها و عملیات لغو", memberships: "محصول‌ها و قراردادهای عضویت", finance: "Ledger، تسویه، فاکتور و بازپرداخت", verifications: "درخواست‌های احراز و تأیید", notifications: "Jobهای اعلان و تمپلیت‌ها", audit: "گزارش ممیزی تغییرات" };
const object = (value: unknown): Record<string, unknown> => value && typeof value === "object" ? value as Record<string, unknown> : {};
const id = (value: unknown) => String(object(value)._id ?? object(value).id ?? "");
const label = (value: unknown, fallback: string) => { const item = object(value); const profile = object(item.profile); const identity = object(profile.identity); return String(profile.name ?? identity.firstName ?? item.name ?? item.mobile ?? item.type ?? fallback); };
const state = (value: unknown) => String(object(value).status ?? object(value).verificationStatus ?? object(object(value).verification).status ?? "ثبت‌شده");
const makeRow = (value: unknown, fallback: string): AdminRow => ({ id: id(value) || crypto.randomUUID(), title: label(value, fallback), detail: String(object(value).type ?? object(value).action ?? object(value).scopeType ?? object(value).createdAt ?? "—"), state: state(value), raw: object(value) });

async function load(domain: AdminP0Domain): Promise<{ rows: AdminRow[]; metrics: string[] }> {
  if (domain === "dashboard") { const [users, orgs, bookings, jobs] = await Promise.all([adminAccessApi.users(adminV2Client, { limit: 1 }), organizationsApi.adminOrganizations(adminV2Client, { limit: 1 }), commerceApi.admin(adminV2Client, { limit: 1 }), notificationsApi.adminJobs(adminV2Client, { limit: 1 })]); return { rows: [], metrics: [`${users.pagination?.total ?? users.items.length} کاربر`, `${orgs.pagination.total} سازمان`, `${bookings.pagination.total} رزرو`, `${jobs.pagination?.total ?? jobs.items.length} job اعلان`] }; }
  if (domain === "users") { const [users, roles] = await Promise.all([adminAccessApi.users(adminV2Client, { limit: 100 }), adminAccessApi.roles(adminV2Client)]); return { rows: [...users.items.map(v => makeRow(v, "کاربر")), ...roles.map(v => makeRow(v, "نقش"))], metrics: [`${users.pagination?.total ?? users.items.length} کاربر`, `${roles.length} نقش`] }; }
  if (domain === "organizations") { const [orgs, clubs, branches] = await Promise.all([organizationsApi.adminOrganizations(adminV2Client, { limit: 100 }), organizationsApi.adminClubs(adminV2Client, { limit: 100 }), organizationsApi.adminBranches(adminV2Client, { limit: 100 })]); return { rows: [...orgs.items.map(v => makeRow(v, "سازمان")), ...clubs.items.map(v => makeRow(v, "باشگاه")), ...branches.items.map(v => makeRow(v, "شعبه"))], metrics: [`${orgs.pagination.total} سازمان`, `${clubs.pagination.total} باشگاه`, `${branches.pagination.total} شعبه`] }; }
  if (domain === "catalog") { const [resources, offerings] = await Promise.all([supplyApi.adminResources(adminV2Client, { limit: 100 }), supplyApi.adminOfferings(adminV2Client, { limit: 100 })]); return { rows: [...resources.items.map(v => makeRow(v, "منبع")), ...offerings.items.map(v => makeRow(v, "خدمت"))], metrics: [`${resources.pagination.total} منبع`, `${offerings.pagination.total} خدمت`] }; }
  if (domain === "bookings") { const result = await commerceApi.admin(adminV2Client, { limit: 100 }); return { rows: result.items.map(v => makeRow(v, "رزرو")), metrics: [`${result.pagination.total} رزرو`] }; }
  if (domain === "memberships") { const [products, contracts] = await Promise.all([membershipsApi.adminList(adminV2Client, "products", { limit: 100 }), membershipsApi.adminList(adminV2Client, "contracts", { limit: 100 })]); return { rows: [...products.items.map(v => makeRow(v, "محصول عضویت")), ...contracts.items.map(v => makeRow(v, "قرارداد عضویت"))], metrics: [`${products.pagination?.total ?? products.items.length} محصول`, `${contracts.pagination?.total ?? contracts.items.length} قرارداد`] }; }
  if (domain === "finance") { const [ledger, settlements, invoices, refunds, reconciliation] = await Promise.all([financeApi.ledger(adminV2Client, { limit: 100 }), financeApi.adminSettlements(adminV2Client, { limit: 100 }), financeApi.adminInvoices(adminV2Client, { limit: 100 }), financeApi.adminRefunds(adminV2Client, { limit: 100 }), financeApi.adminReconciliation(adminV2Client)]); return { rows: [...ledger.items.map(v => makeRow(v, "سند Ledger")), ...settlements.items.map(v => makeRow(v, "تسویه")), ...invoices.items.map(v => makeRow(v, "فاکتور")), ...refunds.items.map(v => makeRow(v, "بازپرداخت"))], metrics: [`${ledger.items.length} سند`, `${settlements.items.length} تسویه`, `تطبیق: ${reconciliation.status}`] }; }
  if (domain === "verifications") { const result = await verificationsApi.admin(adminV2Client, { limit: 100 }); return { rows: result.items.map(v => makeRow(v, "درخواست تأیید")), metrics: [`${result.pagination?.total ?? result.items.length} درخواست`] }; }
  if (domain === "notifications") { const [jobs, templates] = await Promise.all([notificationsApi.adminJobs(adminV2Client, { limit: 100 }), notificationsApi.adminTemplates(adminV2Client)]); return { rows: [...jobs.items.map(v => makeRow(v, "job اعلان")), ...templates.map(v => makeRow(v, "تمپلیت"))], metrics: [`${jobs.pagination?.total ?? jobs.items.length} job`, `${templates.length} تمپلیت`] }; }
  const result = await auditApi.list(adminV2Client, { limit: 100 }); return { rows: result.items.map(v => makeRow(v, "رویداد ممیزی")), metrics: [`${result.pagination.total} رویداد`] };
}

export function AdminP0Screen({ domain }: { domain: AdminP0Domain }) {
  const [rows, setRows] = useState<AdminRow[]>([]); const [metrics, setMetrics] = useState<string[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [pendingId, setPendingId] = useState<string | null>(null);
  const reload = useCallback(async () => { setLoading(true); setError(null); try { const result = await load(domain); setRows(result.rows); setMetrics(result.metrics); } catch (reason) { setError(reason instanceof Error ? reason.message : "دریافت داده ناموفق بود."); } finally { setLoading(false); } }, [domain]);
  useEffect(() => { void reload(); }, [reload]);
  const filtered = useMemo(() => rows.filter(item => `${item.title} ${item.detail} ${item.state}`.toLowerCase().includes(query.trim().toLowerCase())), [query, rows]);
  const act = async (item: AdminRow, action: string) => { setPendingId(item.id); setError(null); try { if (domain === "bookings" && action === "cancel") await commerceApi.adminCancel(adminV2Client, item.id, "لغو توسط ادمین", crypto.randomUUID()); else if (domain === "notifications" && action === "retry") await notificationsApi.retry(adminV2Client, item.id, "تلاش مجدد توسط ادمین"); else if (domain === "verifications") await verificationsApi.review(adminV2Client, item.id, action as "verified" | "rejected", action === "verified" ? "تأیید شد" : "رد شد"); else if (domain === "catalog") await supplyApi.updateAdminStatus(adminV2Client, object(item.raw.profile).type ? "offerings" : "resources", item.id, action); else return; await reload(); } catch (reason) { setError(reason instanceof Error ? reason.message : "عملیات ناموفق بود."); } finally { setPendingId(null); } };
  return <section className="p0-admin-screen"><header><div><span>P0 / P1</span><h1>{titles[domain]}</h1><p>این صفحه فقط از قراردادهای API جدید استفاده می‌کند و داده نمایشی ندارد.</p></div><button onClick={() => void reload()} type="button">به‌روزرسانی</button></header>{error ? <div className="p0-admin-alert" role="alert">{error}</div> : null}<div className="p0-admin-metrics">{metrics.map(value => <strong key={value}>{value}</strong>)}</div>{domain === "dashboard" ? <div className="p0-admin-empty">Gateهای حیاتی: Auth، رزرو، درگاه تستی، Ledger، عضویت، Push/SMS و Audit.</div> : <div className="p0-admin-card"><div className="p0-admin-toolbar"><b>{titles[domain]}</b><input aria-label="جست‌وجو" onChange={event => setQuery(event.target.value)} placeholder="جست‌وجو…" value={query} /></div><div className="p0-admin-table"><table><thead><tr><th>عنوان</th><th>جزئیات</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>{loading ? <tr><td colSpan={4}>در حال دریافت…</td></tr> : filtered.length === 0 ? <tr><td colSpan={4}>داده‌ای ثبت نشده است.</td></tr> : filtered.map(item => <tr key={item.id}><td><b>{item.title}</b><small>{item.id}</small></td><td>{item.detail}</td><td><span>{item.state}</span></td><td><div className="p0-admin-actions">{domain === "bookings" ? <button disabled={pendingId === item.id} onClick={() => void act(item, "cancel")}>لغو</button> : domain === "notifications" ? <button disabled={pendingId === item.id} onClick={() => void act(item, "retry")}>تلاش مجدد</button> : domain === "verifications" ? <><button disabled={pendingId === item.id} onClick={() => void act(item, "verified")}>تأیید</button><button disabled={pendingId === item.id} onClick={() => void act(item, "rejected")}>رد</button></> : domain === "catalog" ? <><button disabled={pendingId === item.id} onClick={() => void act(item, "active")}>فعال</button><button disabled={pendingId === item.id} onClick={() => void act(item, "archived")}>آرشیو</button></> : <span>مشاهده</span>}</div></td></tr>)}</tbody></table></div></div>}</section>;
}
