export const discoveryCoachesSlotsScreenStyles = {
  root: "relative min-h-dvh w-full bg-background",
  main: [
    "flex flex-col gap-6 px-5 pb-[calc(9.5rem+env(safe-area-inset-bottom))] pt-2",
  ].join(" "),
  coachRow: "flex items-center gap-3",
  avatar: "size-12 shrink-0",
  coachMeta: "flex min-w-0 flex-1 flex-col gap-0.5",
  coachName: "truncate text-base leading-tight tracking-tight text-foreground",
  coachSpecialty: "truncate text-sm leading-snug text-muted",
  rating: "flex shrink-0 items-center gap-1 text-foreground",
  ratingValue: "text-sm font-semibold tabular-nums leading-none",
  ratingStar: "shrink-0 text-warning",
  weekRow: "flex items-center justify-between gap-3",
  weekLabel: "min-w-0 flex-1 text-[1.65rem] font-bold tracking-tight text-foreground",
  weekNav: "flex shrink-0 items-center gap-2",
  weekButton: [
    "size-10 shrink-0 rounded-full border-0",
    "bg-foreground text-background shadow-none",
    "data-[hovered=true]:opacity-90 data-[pressed=true]:scale-95",
  ].join(" "),
  weekButtonIcon: "size-[1.125rem] shrink-0 text-background",
  days: "flex flex-col gap-5",
  day: "flex flex-col gap-2.5",
  dayLabel: "text-sm font-bold leading-none tracking-tight text-foreground",
  slotsScroll: "min-w-0 w-full",
  slotsRow: "flex w-max flex-row gap-2.5 pe-1",
  slot: [
    "inline-flex h-14 w-auto min-w-[5.5rem] shrink-0 items-center justify-center",
    "rounded-[14px] border p-2",
    "text-sm font-semibold tabular-nums leading-none shadow-none",
    "transition-[color,background-color,border-color,transform] duration-fast ease-app",
    "outline-none data-[pressed=true]:scale-[0.98]",
  ].join(" "),
  slotAvailable: [
    "cursor-pointer border-border/70 bg-surface text-foreground",
    "hover:bg-surface-secondary data-[hovered=true]:bg-surface-secondary",
  ].join(" "),
  slotUnavailable: [
    "cursor-default border-danger bg-danger/10 text-danger",
    "data-[hovered=true]:bg-danger/10 data-[disabled=true]:opacity-100",
  ].join(" "),
  slotSelected: [
    "border-accent bg-accent/15 text-accent",
    "hover:bg-accent/20 data-[hovered=true]:bg-accent/20",
  ].join(" "),
  footer: "flex w-full flex-col items-center gap-3",
  selectionSummary: "text-center text-sm text-muted",
  bookButton: [
    "h-14 w-full rounded-[1.25rem] border-0",
    "bg-accent text-accent-foreground shadow-none",
    "data-[hovered=true]:opacity-95",
  ].join(" "),
  bookLabel: "text-base font-bold text-accent-foreground",
  bookIcon: "size-5 shrink-0 text-accent-foreground",
  calendarBadge: "absolute end-1.5 top-1.5 size-2 rounded-full bg-accent",
} as const;
