export const athleteBookingsScreenStyles = {
  root: "bg-background",
  content: "flex flex-col gap-6 pb-10 pt-1",
  intro: "flex flex-col gap-2",
  introTitle: "tracking-tight text-foreground",
  introSubtitle: "text-muted",
  list: "flex flex-col gap-4",
  card: "h-auto w-full flex-col items-stretch gap-3 rounded-[24px] border border-border bg-surface p-4 text-start font-normal",
  cardHeader: "flex items-start justify-between gap-3",
  cardTitles: "flex min-w-0 flex-col gap-0.5",
  cardTitle: "text-foreground",
  cardClub: "text-muted",
  cardRows: "flex flex-col gap-2",
  cardRow: "flex items-center gap-2",
  cardRowIcon: "shrink-0 text-muted",
  cardRowText: "text-muted",
  cardFooter: "flex items-center justify-between border-t border-border pt-3",
  cardPrice: "text-foreground",
  empty:
    "flex flex-col items-center gap-2 rounded-[24px] border border-border bg-surface px-6 py-10 text-center",
  emptyTitle: "text-foreground",
  emptyBody: "text-muted",
} as const;
