export const seoCityScreenStyles = {
  root: "min-h-[70dvh] bg-background px-4 py-10 text-foreground sm:px-6 sm:py-14 lg:px-8 lg:py-16",
  header: "mx-auto mb-8 flex w-full min-w-0 max-w-5xl flex-col gap-3 sm:mb-10",
  eyebrow: "text-sm font-medium text-accent",
  title: "text-balance text-3xl font-bold tracking-tight sm:text-4xl lg:text-5xl",
  description: "max-w-3xl leading-8 text-muted",
  meta: "text-muted",
  sections: "mx-auto grid w-full min-w-0 max-w-5xl gap-8 lg:grid-cols-2",
  section: "min-w-0 space-y-4",
  sectionTitle: "text-xl font-bold",
  list: "flex min-w-0 flex-col gap-4",
  item: "rounded-2xl border border-border px-4 py-4 sm:px-5",
  link: "text-lg font-semibold text-accent",
  address: "mt-1 text-sm text-muted",
  empty: "rounded-2xl border border-border p-5 text-sm text-muted",
} as const;
