export type {
  CancelSlotOccurrenceInput,
  ClubClass,
  ClubClassMedia,
  ClubClassesList,
  ClubSlot,
  ClubSlotsList,
  CreateClubClassInput,
  CreateClubSlotInput,
  EntityStatus,
  OccurrenceStatus,
  SlotException,
  SlotExceptionStatus,
  SlotKind,
  SlotRecurrence,
  SlotRecurrenceType,
  SlotSchedule,
  UpdateClubClassInput,
  UpdateClubSlotInput,
} from "../account/club-slots.dto";
