export const discoveryClubsSlotDetailScreenStyles = {
  root: "relative min-h-dvh w-full bg-background",
  scroll: [
    "flex min-h-dvh flex-col",
    "pb-[calc(6.5rem+env(safe-area-inset-bottom))]",
  ].join(" "),
  hero: "relative h-[42dvh] min-h-72 w-full overflow-hidden",
  heroImage: "object-cover object-center",
  heroScrim: [
    "pointer-events-none absolute inset-0",
    "bg-linear-to-t from-background via-background/40 to-background/10",
  ].join(" "),
  sheet: [
    "relative z-10 -mt-14 flex flex-col gap-6",
    "rounded-t-[2.5rem] bg-background px-5 pb-6 pt-7",
  ].join(" "),
  titleBlock: "flex flex-col gap-2",
  category: "text-sm font-medium text-muted",
  title:
    "text-balance text-[1.65rem] leading-tight tracking-tight text-foreground",
  clubTitle: "text-sm text-muted",
  metaGrid: "grid grid-cols-2 gap-2.5",
  metaCell: [
    "flex flex-col gap-1.5 rounded-[1.25rem] border-0",
    "bg-surface px-3.5 py-3",
  ].join(" "),
  metaHeader: "flex items-center gap-1.5",
  metaIcon: "shrink-0 text-muted",
  metaLabel: "text-[0.7rem] text-muted",
  metaValue: "text-sm font-semibold text-foreground",
  section: "flex flex-col gap-3",
  sectionTitle: "text-foreground",
  bodyText: "text-sm leading-relaxed text-muted",
  upcomingList: "flex w-full flex-col gap-2.5",
  upcomingRow: [
    "flex w-full flex-1 items-center justify-between gap-3 rounded-[1.25rem]",
    "border-0 bg-surface px-3.5 py-3",
  ].join(" "),
  upcomingLeading: "flex min-w-0 flex-1 items-center gap-3",
  upcomingIconWrap: [
    "flex size-10 shrink-0 items-center justify-center rounded-[0.875rem]",
    "bg-default text-accent",
  ].join(" "),
  upcomingMeta: "flex min-w-0 flex-col gap-0.5",
  upcomingDate: "text-sm font-semibold text-foreground",
  upcomingTime: "text-xs tabular-nums text-muted",
  upcomingStatus: "shrink-0 text-xs font-semibold",
  upcomingScheduled: "text-success",
  upcomingCancelled: "text-danger",
  viewClass: "w-full",
  footerButton: "h-14 w-full",
} as const;
