export const ownerAnalyticsScreenStyles = {
  root: "bg-background",
  content: "flex flex-col gap-6 pb-10 pt-1",
  intro: "flex flex-col gap-2",
  introTitle: "tracking-tight text-foreground",
  introSubtitle: "text-muted",
  periods:
    "-mx-screen flex gap-2.5 overflow-x-auto px-screen pb-1 [-ms-overflow-style:none] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden",
  periodChip: "shrink-0 rounded-full",
  statsGrid: "grid grid-cols-2 gap-4",
  chartCard:
    "flex flex-col gap-3 rounded-[24px] border-0 bg-surface p-4 shadow-sm shadow-foreground/5",
  chartTitle: "text-foreground",
  chartHint: "text-muted",
  chart: "w-full",
  barRows: "flex flex-col gap-3",
  barRow: "flex flex-col gap-1.5",
  barRowHeader: "flex items-center justify-between gap-3",
  barRowLabel: "text-foreground",
  barRowValue: "shrink-0 text-sm text-muted",
  barTrack: "block h-2 w-full overflow-hidden rounded-full bg-default",
  barFill: "block h-full rounded-full bg-accent",
  funnelSteps: "flex flex-col gap-4",
  funnelStep: "flex flex-col gap-1.5",
  funnelHeader: "flex items-center justify-between gap-3",
  funnelLabelGroup: "flex items-center gap-2",
  funnelLabel: "text-foreground",
  funnelValue: "shrink-0 text-sm font-medium text-foreground",
} as const;
