export {
  ApiClient,
  createApiClient,
  type ApiClientOptions,
  type RequestOptions,
} from "./client";
export { ApiError, KYC_REQUIRED_CODE, isKycRequiredError } from "./errors";
export {
  ACCOUNT_SESSION_KEY,
  ADMIN_SESSION_KEY,
  createLocalStorage,
  createMemoryStorage,
  type TokenStorage,
} from "./storage";
export type {
  ApiErrorBody,
  ApiErrorMessage,
  AuthSession,
  ChoiceGroup,
  ChoiceOption,
  ClubLifecycleStatus,
  AthleteBodyType,
  AthleteDiet,
  AthleteExperience,
  AthleteMood,
  BloodGroup,
  RhFactor,
  ArticleAudience,
  ArticleKind,
  BannerLinkKind,
  BookingActor,
  BookingResourceType,
  BookingStatus,
  CoachSlotStatus,
  ConsultationKind,
  BannerPlacement,
  FaqAudience,
  GeoCoordinates,
  ItemsResponse,
  KycDocumentType,
  KycRequestKind,
  KycRequestStatus,
  KycStatus,
  LocationKind,
  LocationNode,
  Paginated,
  PaginationMeta,
  Privacy,
  PublicUser,
  PublishStatus,
  RefItem,
  RefStatus,
  RefType,
  Role,
  SportKind,
  SportNode,
  SuccessResponse,
  SupportMessageAuthorKind,
  SupportRelatedEntityKind,
  SupportTicketCategory,
  SupportTicketPriority,
  SupportTicketStatus,
  NotificationReadStatus,
  DevicePlatform,
  TokenPair,
  UserStatus,
  VerificationStatus,
} from "./types";
// React bindings intentionally NOT re-exported here — client-only code
// (createContext) must stay out of server bundles. Use "@repo/api/react".
export {
  createAccountAuthApi,
  createAdminAuthApi,
  type AccountAuthApi,
  type AdminAuthApi,
  type AdminConfirmOtpInput,
  type ConfirmOtpInput,
  type ForgotPasswordConfirmInput,
  type ForgotPasswordInput,
  type LoginInput,
  type LogoutInput,
  type OtpRequested,
  type RequestOtpInput,
  type ResetPasswordInput,
  type SetPasswordInput,
  type SwitchRoleInput,
} from "./auth";
export {
  CLUB_SOCIAL_PLATFORM_WEBSITE,
  clubWebsiteFromSocials,
  upsertClubWebsiteSocial,
  createAccountClubsApi,
  createClubOwnerClubsApi,
  createAccountClubSlotsApi,
  createClubOwnerClubSlotsApi,
  createAccountKycApi,
  createAccountProfileApi,
  createAccountReferralApi,
  createAccountRolesApi,
  createAccountSupportApi,
  createAccountNotificationsApi,
  type AccountNotificationsApi,
  type ListNotificationsQuery,
  type NotificationInbox,
  type NotificationItem,
  type NotificationPreferences,
  type RegisterDeviceInput,
  type RegisterDeviceResult,
  type UpdateNotificationPreferencesInput,
  type AccountClubsApi,
  type AccountClubSlotsApi,
  type AccountKycApi,
  type AccountProfileApi,
  type AccountReferralApi,
  type AccountRolesApi,
  type AccountSupportApi,
  type CreateSupportTicketInput,
  type ListMySupportTicketsQuery,
  type ListPublicFaqQuery,
  type PublicFaqItem,
  type ReplySupportTicketInput,
  type SupportContact,
  type SupportRelatedEntity,
  type SupportTicket,
  type SupportTicketDetail,
  type SupportTicketMessage,
  type SupportUserSummary,
  type AdminCreateClubInput,
  type ApplyRoleInput,
  type ApplyRoleResponse,
  type RoleAction,
  type RoleActionNextStep,
  type RoleAvailability,
  type RoleOverviewResponse,
  type RoleRequest,
  type RoleRequestAdminItem,
  type SubmitRoleRequestInput,
  type SubmitRoleRequestResponse,
  type AthleteBloodType,
  type AthleteHealth,
  type AthleteLifestyle,
  type AthleteProfile,
  type Club,
  type ClubClass,
  type ClubLocationNode,
  type ClubOperationalStatus,
  type ClubOwnerClubsApi,
  type ClubOwnerClubSlotsApi,
  type ClubRefItem,
  type ClubSlot,
  type ClubSportItem,
  type ClubUserReview,
  type CoachProfile,
  type CreateClubClassInput,
  type CreateClubInput,
  type CreateClubSlotInput,
  type GeoDirection,
  type RulePolicy,
  type InviteInput,
  type InviteResponse,
  type KycDocumentRequest,
  type KycStatusResponse,
  type MyReferralResponse,
  type ReferralInvite,
  type SlotKind,
  type SlotRecurrenceType,
  type SubmitClubReviewInput,
  type SubmitCoachVerificationInput,
  type SubmitIdentityInput,
  type UpdateAddressInput,
  type UpdateAthleteHealthInput,
  type UpdateAthleteLifestyleInput,
  type UpdateAthleteProfileInput,
  type UpdateClubClassInput,
  type UpdateClubInput,
  type UpdateClubSlotInput,
  type UpdateCoachProfileInput,
  type UpdateMeInput,
  type ProfileSettings,
  type UpdateProfileSettingsInput,
  type ValidateReferralResponse,
  type OperatingHourAudience,
  type WeekdayStatus,
  createAccountGamificationApi,
  type AccountGamificationApi,
  type AchievementState,
  type GamificationSubjectType,
  type GamificationSummary,
  type ListMyPointTransactionsQuery,
  type MyAchievement,
  type PointsSummary,
  type PointTransactionItem,
  type PointTransactionReason,
} from "./account";
export {
  createDiscoveryClubsApi,
  createDiscoveryClubSlotsApi,
  createDiscoveryCoachesApi,
  createDiscoveryCoachSlotsApi,
  type CreateDiscoveryReviewInput,
  type DiscoveryClubsApi,
  type DiscoveryClubSlotsApi,
  type DiscoveryCoachesApi,
  type DiscoveryCoachSlotsApi,
  type DiscoveryClubsQuery,
  type DiscoveryCoach,
  type DiscoveryCoachesQuery,
  type CoachSlot,
  type CoachSlotClub,
  type CoachSlotsRangeQuery,
  type CoachSlotsResponse,
  type ClubCalendarQuery,
  type ClubCalendarResponse,
} from "./discovery";
export {
  createAccountBookingsApi,
  createClubBookingsApi,
  createCoachBookingsApi,
  createCoachSlotsApi,
  type AccountBookingsApi,
  type Booking,
  type BookingCancellationPreview,
  type BookingOccurrence,
  type BookingResource,
  type BookingsListQuery,
  type CancelBookingInput,
  type CancelBookingSeriesInput,
  type CancelBookingSeriesResult,
  type ClubBookingsApi,
  type CoachBookingsApi,
  type CoachSlotsApi,
  type CoachSlotsListResponse,
  type CoachSlotInput,
  type CreateBookingInput,
  type CreateClubBookingInput,
  type CreateClubBookingResult,
  type CreateCoachSlotsInput,
  type PayBookingResult,
  type RescheduleBookingInput,
  type VerifyBookingPaymentInput,
} from "./booking";
export {
  createAccountProgressApi,
  type AccountProgressApi,
  type AthleteDataGrant,
  type AthleteDataGrantScope,
  type AthleteDataGrantStatus,
  type ConsentHistoryEvent,
  type ConsentHistoryResult,
  type CreateAthleteDataGrantInput,
  type CreateMetricGoalInput,
  type CreateProgressMetricInput,
  type DeleteProgressMetricsInput,
  type DeleteProgressMetricsResult,
  type Exercise,
  type HealthSyncProvider,
  type HealthSyncState,
  type HealthSyncStatus,
  type MetricGoal,
  type MetricGoalOperator,
  type MetricGoalPeriod,
  type MetricGoalStatus,
  type MetricReminder,
  type MetricReminderStatus,
  type MetricType,
  type MetricSource,
  type MetricsSummaryItem,
  type MetricsSummaryResult,
  type MetricValueKind,
  type PersonalRecord,
  type ProgressExportPayload,
  type ProgressMetric,
  type ProgressPhoto,
  type SyncProgressMetricInput,
  type SyncProgressMetricsInput,
  type SyncProgressMetricsResult,
  type UpdateMetricGoalInput,
  type UpsertHealthSyncStateInput,
  type UpsertMetricReminderInput,
  type WorkoutLog,
  type WorkoutLogSetInput,
  type WorkoutPlan,
  type WorkoutProgram,
  type WorkoutProgramStatus,
} from "./progress";
export {
  createAccountFinanceApi,
  type AccountFinanceApi,
  type AnalyticsPeriod,
  type CreatePayoutInput,
  type DraftPeriodPayoutInput,
  type Invoice,
  type InvoicesPage,
  type InvoiceStatus,
  type ListInvoicesQuery,
  type ListPaymentsQuery,
  type ListPayoutsQuery,
  type OwnerFinanceAnalytics,
  type PaymentChannel,
  type PaymentPurpose,
  type PaymentRecord,
  type PaymentsPage,
  type PaymentStatus,
  type PaymentWithLedger,
  type Payout,
  type PayoutsPage,
  type PayoutStatus,
  type ResolvePayoutDisputeInput,
  type WalletOverview,
} from "./finance";
export {
  createAccountCoachingApi,
  type AccountCoachingApi,
  type CoachAnalyticsOverview,
  type CoachMessage,
  type CoachStudent,
  type CoachStudentEngagementLevel,
  type CoachThread,
  type SessionPackage,
  type SessionPackagesPage,
  type SessionPackageStatus,
} from "./coaching";
export {
  createAccountSocialApi,
  createSocialApi,
  type AccountSocialApi,
  type SocialApi,
  type SocialComment,
  type SocialFollow,
  type SocialPost,
  type SocialReport,
} from "./social";
export {
  createAccountNutritionApi,
  type AccountNutritionApi,
  type FoodItem,
  type MealAdherence,
  type MealPlan,
} from "./nutrition";
export {
  createClubStaffApi,
  type ClubStaffApi,
  type ClubStaffMember,
  type StaffPermissionKey,
  type StaffRolePreset,
} from "./staff";
export {
  createAccountOpsApi,
  type AccountOpsApi,
  type OwnerTask,
  type OwnerTasksSummary,
} from "./ops";
export {
  createBasicsLocationsApi,
  createBasicsSportsApi,
  createBasicsRefsApi,
  createBasicsChoicesApi,
  type BasicsLocationsApi,
  type BasicsSportsApi,
  type BasicsRefsApi,
  type BasicsChoicesApi,
  type BasicsRefListResponse,
  type LocationChildrenResponse,
  type ListSportsQuery,
  type PublicChoiceGroup,
  type SportChildrenResponse,
} from "./basics";
export {
  createAnalyticsApi,
  type AnalyticsApi,
  type CaptureAttributionInput,
  type TouchPoint,
  type UserAttribution,
} from "./analytics";
export { createMediaApi, type MediaApi, type MediaAsset } from "./media";
export {
  createArticlesApi,
  type Article,
  type ArticleAuthor,
  type ArticleComment,
  type ArticleEngagement,
  type ArticleFacets,
  type ArticleSeo,
  type ArticleSummary,
  type ArticleTaxonomy,
  type ArticleViewerState,
  type ArticlesApi,
  type ListArticlesQuery,
} from "./articles";
export {
  createBannersApi,
  type Banner,
  type BannerSlide,
  type BannersApi,
  type ListBannersQuery,
} from "./banners";
export {
  createAdminBasicsApi,
  createAdminArticlesApi,
  createAdminBannersApi,
  createAdminClubsApi,
  createAdminClubSlotsApi,
  createAdminFinanceApi,
  createAdminGamificationApi,
  type AdminGamificationApi,
  type AchievementGrantMode,
  type AchievementMetric,
  type AdjustPointsInput,
  type AdjustPointsResult,
  type AdminAchievement,
  type AdminAchievementGrant,
  type AdminPointRule,
  type CreateAchievementInput,
  type CreatePointRuleInput,
  type GamificationOverview,
  type GrantAchievementSubjectInput,
  type ListAdminAchievementsQuery,
  type ListAdminGrantsQuery,
  type ListAdminPointRulesQuery,
  type ListAdminPointTransactionsQuery,
  type PointRuleEvent,
  type PointRuleRepeat,
  type UpdateAchievementInput,
  type UpdatePointRuleInput,
  createAdminKycApi,
  createAdminAuditApi,
  createAdminSupportApi,
  createAdminUsersApi,
  createAdminVerificationApi,
  createAdminBookingsApi,
  createAdminSocialApi,
  createAdminNutritionApi,
  type AdminBasicsApi,
  type AdminArticle,
  type AdminArticlesApi,
  type AdminBanner,
  type AdminBannersApi,
  type AdminBookingsApi,
  type AdminBookingsListQuery,
  type AdminFinanceApi,
  type AdminLedgerEntry,
  type AdminLedgerPage,
  type AdminNutritionApi,
  type AdminSocialApi,
  type AdminSocialReportsPage,
  type ListAdminLedgerQuery,
  type ListAdminSocialReportsQuery,
  type ResolveSocialReportInput,
  type BannerScheduleInput,
  type BannerSlideInput,
  type CreateBannerInput,
  type CreateFoodItemInput,
  type ListAdminBannersQuery,
  type UpdateBannerInput,
  type UpdateFoodItemInput,
  type AdminClubsApi,
  type AdminClubSlotsApi,
  type AdminChoiceOptionInput,
  type AdminCreateChoiceGroupInput,
  type AdminCreateLocationInput,
  type AdminCreateRefItemInput,
  type AdminCreateSportInput,
  type AdminCreateUserInput,
  type AdminKycApi,
  type AdminKycRequest,
  type AdminKycUserSummary,
  type AdminFaqItem,
  type AdminRefListResponse,
  type AdminAuditApi,
  type AdminSupportApi,
  type AdminUpdateTicketInput,
  type CreateArticleInput,
  type CreateFaqInput,
  type ListAdminArticlesQuery,
  type ListAdminFaqQuery,
  type ListAdminSupportTicketsQuery,
  type UpdateArticleInput,
  type UpdateFaqInput,
  type AdminUpdateChoiceGroupInput,
  type AdminUpdateLocationInput,
  type AdminUpdateRefItemInput,
  type AdminUpdateSportInput,
  type AdminUpdateUserInput,
  type AdminUpdateUserRolesInput,
  type AdminUpdateUserStatusInput,
  type AdminUserActivationInput,
  type AdminUsersApi,
  type AdminVerificationApi,
  type CoachVerificationItem,
  type CoachVerificationUser,
  type ListAdminKycQuery,
  type ListAdminLocationsQuery,
  type ListAdminSportsQuery,
  type ListAdminUsersQuery,
  type ListClubReviewsQuery,
  type ListCoachVerificationsQuery,
  type ReviewCoachResponse,
  type ReviewKycInput,
  type ReviewVerificationInput,
  createAdminAnalyticsApi,
  type AdminAnalyticsApi,
  type AdminAnalyticsOverview,
  type DailyPoint,
  createAdminNotificationTemplatesApi,
  type AdminNotificationTemplatesApi,
  type CreateNotificationTemplateInput,
  type ListNotificationTemplatesQuery,
  type NotificationChannelSetting,
  type NotificationSmsSetting,
  type NotificationTemplate,
  type NotificationTemplatesResponse,
  type UpdateNotificationTemplateInput,
  createAdminProgressApi,
  type AdminProgressApi,
  type AdminExercisesPage,
  type AdminMetricTypesPage,
  type CreateExerciseInput,
  type CreateMetricTypeInput,
  type ListAdminExercisesQuery,
  type ListAdminMetricTypesQuery,
  type UpdateExerciseInput,
  type UpdateMetricTypeInput,
  type VerifyExerciseInput,
  createAdminCoachingApi,
  type AdminCoachingApi,
  type AdminCoachService,
  type AdminCoachServicesPage,
  type AdminCoachStudentsPage,
  type AdminHealthAssessment,
  type AdminListCoachingQuery,
  type AdminSessionPackagesPage,
  createAdminMembershipsApi,
  type AdminMembershipsApi,
  type AdminPlatformPlansPage,
  type AdminPlatformSubscriptionsPage,
  type CreatePlatformPlanInput,
  type ListAdminPlatformPlansQuery,
  type ListAdminPlatformSubscriptionsQuery,
  type UpdatePlatformPlanInput,
  type AdminLedgerLine,
  type LedgerEntryKind,
  type ListAdminPaymentsQuery,
  type SettlePayoutInput,
  type SocialReportStatus,
  type FoodItemsPage,
  type FoodItemStatus,
  type ListFoodItemsQuery,
  type AuditLogItem,
  type AuditLogsPage,
  type ImpersonationSession,
  type ListAuditLogsQuery,
  type StartImpersonationInput,
  type StartImpersonationResult,
} from "./admin";
export {
  createAccountMembershipsApi,
  type AccountMembershipsApi,
  type CancelMembershipInput,
  type ClubMembership,
  type ClubMembershipPlan,
  type ConsumeMembershipCreditInput,
  type ImportMembershipRow,
  type ImportMembershipsInput,
  type ImportMembershipsResult,
  type ListClubMembershipsQuery,
  type ListMyMembershipsQuery,
  type MembershipPlanKind,
  type MembershipStatus,
  type MembershipsPage,
  type PlatformPlan,
  type PlatformSubscription,
  type SelfPurchaseMembershipInput,
  type SellMembershipInput,
  type TransferMembershipInput,
} from "./memberships";
export {
  createAccountCheckinApi,
  type AccountCheckinApi,
  type CheckIn,
  type CheckInByBookingCodeInput,
  type CheckInByMembershipInput,
  type CheckinDevice,
  type CheckInMethod,
  type CheckInsPage,
  type ListCheckInsQuery,
  type ProvisionCheckinDeviceInput,
  type ProvisionCheckinDeviceResult,
  type OfflineCheckInItemInput,
  type SyncOfflineBatchInput,
  type SyncOfflineBatchItemResult,
  type SyncOfflineBatchResult,
} from "./checkin";
export {
  createAccountWaitlistApi,
  type AccountWaitlistApi,
  type ClaimWaitlistInput,
  type ExpireWaitlistOffersResult,
  type JoinWaitlistInput,
  type ListWaitlistsQuery,
  type OfferWaitlistInput,
  type Waitlist,
  type WaitlistEntry,
  type WaitlistEntryStatus,
  type WaitlistStatus,
  type WaitlistsPage,
} from "./waitlist";
export {
  createAccountLifecycleApi,
  type AccountLifecycleApi,
  type AtRiskMemberRow,
  type AtRiskMembersResponse,
  type LifecycleJourney,
  type LifecycleSegment,
  type LifecycleSegmentKind,
} from "./lifecycle";
export {
  createAccountCalendarApi,
  type AccountCalendarApi,
  type CalendarBlock,
  type CalendarBlockReason,
  type CalendarBlocksPage,
  type CalendarResourceType,
  type UpsertCalendarBlockInput,
} from "./calendar";
export {
  createAppConfigApi,
  appConfigEndpoints,
  appConfigKeys,
  type AppBootstrap,
  type AppBootstrapFeature,
  type AppConfigApi,
  type AppPlatform,
  type AppReleaseNotes,
  type FeatureFlag,
  type FeatureFlagRule,
  type FeatureFlagRuleInput,
  type FeatureFlagStatus,
  type FetchBootstrapQuery,
  type MobileReleasePolicy,
  type ReleaseChannel,
  type UpsertFeatureFlagInput,
  type UpsertReleasePolicyInput,
} from "./app-config";
