export {
  ApiClient,
  createApiClient,
  type ApiClientOptions,
  type RequestOptions,
} from "./client";
export { ApiError, KYC_REQUIRED_CODE, isKycRequiredError } from "./errors";
export {
  ACCOUNT_SESSION_KEY,
  ADMIN_SESSION_KEY,
  createLocalStorage,
  createMemoryStorage,
  type TokenStorage,
} from "./storage";
export type {
  ApiErrorBody,
  AuthSession,
  ChoiceGroup,
  ChoiceOption,
  ClubLifecycleStatus,
  ArticleAudience,
  ArticleKind,
  FaqAudience,
  GeoCoordinates,
  ItemsResponse,
  KycDocumentType,
  KycRequestKind,
  KycRequestStatus,
  KycStatus,
  LocationKind,
  LocationNode,
  Paginated,
  PaginationMeta,
  Privacy,
  PublicUser,
  PublishStatus,
  RefItem,
  RefStatus,
  RefType,
  Role,
  SportKind,
  SportNode,
  SuccessResponse,
  SupportMessageAuthorKind,
  SupportRelatedEntityKind,
  SupportTicketCategory,
  SupportTicketPriority,
  SupportTicketStatus,
  NotificationReadStatus,
  DevicePlatform,
  TokenPair,
  UserStatus,
  VerificationStatus,
} from "./types";
// React bindings intentionally NOT re-exported here — client-only code
// (createContext) must stay out of server bundles. Use "@repo/api/react".
export {
  createAccountAuthApi,
  createAdminAuthApi,
  type AccountAuthApi,
  type AdminAuthApi,
  type AdminConfirmOtpInput,
  type ConfirmOtpInput,
  type ForgotPasswordConfirmInput,
  type ForgotPasswordInput,
  type LoginInput,
  type LogoutInput,
  type OtpRequested,
  type RequestOtpInput,
  type ResetPasswordInput,
  type SetPasswordInput,
  type SwitchRoleInput,
} from "./auth";
export {
  createAccountClubsApi,
  createClubOwnerClubsApi,
  createAccountClubSlotsApi,
  createClubOwnerClubSlotsApi,
  createAccountKycApi,
  createAccountProfileApi,
  createAccountReferralApi,
  createAccountRolesApi,
  createAccountSupportApi,
  createAccountNotificationsApi,
  type AccountNotificationsApi,
  type ListNotificationsQuery,
  type NotificationInbox,
  type NotificationItem,
  type RegisterDeviceInput,
  type RegisterDeviceResult,
  type AccountClubsApi,
  type AccountClubSlotsApi,
  type AccountKycApi,
  type AccountProfileApi,
  type AccountReferralApi,
  type AccountRolesApi,
  type AccountSupportApi,
  type CreateSupportTicketInput,
  type ListMySupportTicketsQuery,
  type ListPublicFaqQuery,
  type PublicFaqItem,
  type ReplySupportTicketInput,
  type SupportContact,
  type SupportRelatedEntity,
  type SupportTicket,
  type SupportTicketDetail,
  type SupportTicketMessage,
  type SupportUserSummary,
  type AdminCreateClubInput,
  type ApplyRoleInput,
  type ApplyRoleResponse,
  type AthleteProfile,
  type Club,
  type ClubClass,
  type ClubLocationNode,
  type ClubOperationalStatus,
  type ClubOwnerClubsApi,
  type ClubOwnerClubSlotsApi,
  type ClubRefItem,
  type ClubSlot,
  type ClubSportItem,
  type ClubUserReview,
  type CoachProfile,
  type CreateClubClassInput,
  type CreateClubInput,
  type CreateClubSlotInput,
  type GeoDirection,
  type RulePolicy,
  type InviteInput,
  type InviteResponse,
  type KycDocumentRequest,
  type KycStatusResponse,
  type MyReferralResponse,
  type ReferralInvite,
  type SlotKind,
  type SlotRecurrenceType,
  type SubmitClubReviewInput,
  type SubmitCoachVerificationInput,
  type SubmitIdentityInput,
  type UpdateAthleteProfileInput,
  type UpdateClubClassInput,
  type UpdateClubInput,
  type UpdateClubSlotInput,
  type UpdateCoachProfileInput,
  type UpdateMeInput,
  type ValidateReferralResponse,
  type OperatingHourAudience,
  type WeekdayStatus,
} from "./account";
export {
  createDiscoveryClubsApi,
  createDiscoveryClubSlotsApi,
  createDiscoveryCoachesApi,
  type CreateDiscoveryReviewInput,
  type DiscoveryClubsApi,
  type DiscoveryClubSlotsApi,
  type DiscoveryCoachesApi,
  type DiscoveryClubsQuery,
  type DiscoveryCoach,
  type DiscoveryCoachesQuery,
  type ClubCalendarQuery,
  type ClubCalendarResponse,
} from "./discovery";
export {
  createBasicsLocationsApi,
  createBasicsSportsApi,
  createBasicsRefsApi,
  type BasicsLocationsApi,
  type BasicsSportsApi,
  type BasicsRefsApi,
  type BasicsRefListResponse,
  type LocationChildrenResponse,
  type ListSportsQuery,
  type SportChildrenResponse,
} from "./basics";
export {
  createAnalyticsApi,
  type AnalyticsApi,
  type CaptureAttributionInput,
  type TouchPoint,
  type UserAttribution,
} from "./analytics";
export { createMediaApi, type MediaApi, type MediaAsset } from "./media";
export {
  createArticlesApi,
  type Article,
  type ArticleAuthor,
  type ArticleComment,
  type ArticleEngagement,
  type ArticleFacets,
  type ArticleSeo,
  type ArticleSummary,
  type ArticleTaxonomy,
  type ArticleViewerState,
  type ArticlesApi,
  type ListArticlesQuery,
} from "./articles";
export {
  createAdminBasicsApi,
  createAdminArticlesApi,
  createAdminClubsApi,
  createAdminClubSlotsApi,
  createAdminKycApi,
  createAdminSupportApi,
  createAdminUsersApi,
  createAdminVerificationApi,
  type AdminBasicsApi,
  type AdminArticle,
  type AdminArticlesApi,
  type AdminClubsApi,
  type AdminClubSlotsApi,
  type AdminChoiceOptionInput,
  type AdminCreateChoiceGroupInput,
  type AdminCreateLocationInput,
  type AdminCreateRefItemInput,
  type AdminCreateSportInput,
  type AdminCreateUserInput,
  type AdminKycApi,
  type AdminKycRequest,
  type AdminKycUserSummary,
  type AdminFaqItem,
  type AdminRefListResponse,
  type AdminSupportApi,
  type AdminUpdateTicketInput,
  type CreateArticleInput,
  type CreateFaqInput,
  type ListAdminArticlesQuery,
  type ListAdminFaqQuery,
  type ListAdminSupportTicketsQuery,
  type UpdateArticleInput,
  type UpdateFaqInput,
  type AdminUpdateChoiceGroupInput,
  type AdminUpdateLocationInput,
  type AdminUpdateRefItemInput,
  type AdminUpdateSportInput,
  type AdminUpdateUserInput,
  type AdminUpdateUserRolesInput,
  type AdminUpdateUserStatusInput,
  type AdminUserActivationInput,
  type AdminUsersApi,
  type AdminVerificationApi,
  type CoachVerificationItem,
  type CoachVerificationUser,
  type ListAdminKycQuery,
  type ListAdminLocationsQuery,
  type ListAdminSportsQuery,
  type ListAdminUsersQuery,
  type ListClubReviewsQuery,
  type ListCoachVerificationsQuery,
  type ReviewCoachResponse,
  type ReviewKycInput,
  type ReviewVerificationInput,
} from "./admin";
