/** Lowercase English API message → `Api.exact.*` key. */
export const EXACT_API_MESSAGES: Record<string, string> = {
  "a favourite location needs a map pin or an address": "aFavouriteLocationNeedsAMapPinOrAnAddress",
  "a partial booking retry exists; refresh bookings before retrying": "aPartialBookingRetryExistsRefreshBookingsBeforeRetrying",
  "a slot already exists at that time": "aSlotAlreadyExistsAtThatTime",
  "account is not active": "accountIsNotActive",
  "active data grant is required": "activeDataGrantIsRequired",
  "active role is no longer assigned": "activeRoleIsNoLongerAssigned",
  "admin access required": "adminAccessRequired",
  "admin role cannot be activated via account auth": "adminRoleCannotBeActivatedViaAccountAuth",
  "affiliation already exists for this club": "affiliationAlreadyExistsForThisClub",
  "already on this waitlist": "alreadyOnThisWaitlist",
  "already verified": "alreadyVerified",
  "amount exceeds remaining balance": "amountExceedsRemainingBalance",
  "amount must be non-zero": "amountMustBeNonZero",
  "an identity check is already pending": "anIdentityCheckIsAlreadyPending",
  "an open cash shift already exists for this club": "anOpenCashShiftAlreadyExistsForThisClub",
  "at least one document is required": "atLeastOneDocumentIsRequired",
  "athleteid required for coach view": "athleteidRequiredForCoachView",
  "athletes can only manage their own plans": "athletesCanOnlyManageTheirOwnPlans",
  "athleteuserid is required": "athleteuseridIsRequired",
  "athleteuserid is required for coach view": "athleteuseridIsRequiredForCoachView",
  "athleteuserid required to convert a lead": "athleteuseridRequiredToConvertALead",
  "attendeecount exceeds the occurrence capacity": "attendeecountExceedsTheOccurrenceCapacity",
  "authentication required": "authenticationRequired",
  "automatic achievements require a grant rule (metric + threshold)": "automaticAchievementsRequireAGrantRuleMetricThreshold",
  "booking already uses this occurrence": "bookingAlreadyUsesThisOccurrence",
  "booking already uses this slot": "bookingAlreadyUsesThisSlot",
  "booking can no longer be cancelled": "bookingCanNoLongerBeCancelled",
  "booking can no longer be rescheduled": "bookingCanNoLongerBeRescheduled",
  "booking has no occupied coach slot": "bookingHasNoOccupiedCoachSlot",
  "booking has no occupied occurrence": "bookingHasNoOccupiedOccurrence",
  "booking has no refundable payment": "bookingHasNoRefundablePayment",
  "booking is not awaiting coach approval": "bookingIsNotAwaitingCoachApproval",
  "booking is not awaiting payment": "bookingIsNotAwaitingPayment",
  "cannot add/remove option values on a system choice group": "cannotAddRemoveOptionValuesOnASystemChoiceGroup",
  "cannot assign an archived program": "cannotAssignAnArchivedProgram",
  "cannot change block resource on upsert": "cannotChangeBlockResourceOnUpsert",
  "cannot comment on this post": "cannotCommentOnThisPost",
  "cannot create a branch of a branch": "cannotCreateABranchOfABranch",
  "cannot delete a club that still has branches": "cannotDeleteAClubThatStillHasBranches",
  "cannot delete a location that still has children": "cannotDeleteALocationThatStillHasChildren",
  "cannot delete a sport node that still has children": "cannotDeleteASportNodeThatStillHasChildren",
  "cannot delete a system choice group": "cannotDeleteASystemChoiceGroup",
  "cannot follow yourself": "cannotFollowYourself",
  "cannot like this post": "cannotLikeThisPost",
  "cannot reply to a closed ticket": "cannotReplyToAClosedTicket",
  "cannot resolve offline reconciliation in its current status": "cannotResolveOfflineReconciliationInItsCurrentStatus",
  "cash shift is already closed": "cashShiftIsAlreadyClosed",
  "choice key already exists": "choiceKeyAlreadyExists",
  "classid is required for class slots": "classidIsRequiredForClassSlots",
  "club is not pending review": "clubIsNotPendingReview",
  "club resource id must match path clubid": "clubResourceIdMustMatchPathClubid",
  "clubid must reference an active club the coach is affiliated with": "clubidMustReferenceAnActiveClubTheCoachIsAffiliatedWith",
  "coach does not offer this consultation type": "coachDoesNotOfferThisConsultationType",
  "coach verification is not pending": "coachVerificationIsNotPending",
  "coaches may only block coach resources": "coachesMayOnlyBlockCoachResources",
  "code expired or not requested": "codeExpiredOrNotRequested",
  "confirmation must be delete_metrics": "confirmationMustBeDeleteMetrics",
  "could not allocate a ticket number": "couldNotAllocateATicketNumber",
  "could not allocate unique slug": "couldNotAllocateUniqueSlug",
  "coupon code already exists": "couponCodeAlreadyExists",
  "coupon has expired": "couponHasExpired",
  "coupon is not active yet": "couponIsNotActiveYet",
  "coupon is not valid for this club": "couponIsNotValidForThisClub",
  "coupon redemption limit reached": "couponRedemptionLimitReached",
  "checkout idempotency key has different semantics": "checkoutIdempotencyKeyHasDifferentSemantics",
  "checkout initiation is in progress": "checkoutInitiationIsInProgress",
  "currentpassword is required": "currentpasswordIsRequired",
  "custom preset requires an explicit permissions list": "customPresetRequiresAnExplicitPermissionsList",
  "date is required": "dateIsRequired",
  "date is required for once slots": "dateIsRequiredForOnceSlots",
  "document file is missing on disk": "documentFileIsMissingOnDisk",
  "duration memberships do not consume session/entry credit": "durationMembershipsDoNotConsumeSessionEntryCredit",
  "durationdays is required for duration plans": "durationdaysIsRequiredForDurationPlans",
  "each offline item needs bookingcode or membershipid+userid": "eachOfflineItemNeedsBookingcodeOrMembershipidUserid",
  "invalid offline snapshot token": "invalidOfflineSnapshotToken",
  "endson must be on/after startson": "endsonMustBeOnAfterStartson",
  "endtime must be after starttime": "endtimeMustBeAfterStarttime",
  "entriestotal is required for entries plans": "entriestotalIsRequiredForEntriesPlans",
  "expiresat must be in the future": "expiresatMustBeInTheFuture",
  "external banner links must be absolute http(s) urls": "externalBannerLinksMustBeAbsoluteHttpSUrls",
  "file missing in storage": "fileMissingInStorage",
  "freeze is not allowed for this plan": "freezeIsNotAllowedForThisPlan",
  "free membership plans do not require gateway checkout": "freeMembershipPlansDoNotRequireGatewayCheckout",
  "from must be before to": "fromMustBeBeforeTo",
  "hardware event needs bookingcode or membershipid+userid": "hardwareEventNeedsBookingcodeOrMembershipidUserid",
  "offline events must sync in sequence": "offlineEventsMustSyncInSequence",
  "offline reconciliation changed; reload": "offlineReconciliationChangedReload",
  "offline reconciliation resolution limit reached": "offlineReconciliationResolutionLimitReached",
  "offline sequence or nonce payload drift": "offlineSequenceOrNoncePayloadDrift",
  "offline snapshot binding mismatch": "offlineSnapshotBindingMismatch",
  "offline snapshot is revoked or expired": "offlineSnapshotIsRevokedOrExpired",
  "offline snapshot was invalidated by credential rotation": "offlineSnapshotWasInvalidatedByCredentialRotation",
  "rejected security events cannot be retried": "rejectedSecurityEventsCannotBeRetried",
  "holder must include userid or guest { name, phone }": "holderMustIncludeUseridOrGuestNamePhone",
  "holder.userid or holder.guest is required": "holderUseridOrHolderGuestIsRequired",
  "idempotency key is already used by another payment": "idempotencyKeyIsAlreadyUsedByAnotherPayment",
  "idempotency key is already used with a different payment payload": "idempotencyKeyIsAlreadyUsedWithADifferentPaymentPayload",
  "identity already verified": "identityAlreadyVerified",
  "identity.name is required": "identityNameIsRequired",
  "impersonation session has ended": "impersonationSessionHasEnded",
  "insufficient wallet balance": "insufficientWalletBalance",
  "internal banner links must be app-relative paths starting with /": "internalBannerLinksMustBeAppRelativePathsStartingWith",
  "invalid amount split: net cannot be negative": "invalidAmountSplitNetCannotBeNegative",
  "invalid clubid": "invalidClubid",
  "invalid coachid": "invalidCoachid",
  "invalid code": "invalidCode",
  "invalid credentials": "invalidCredentials",
  "invalid date range": "invalidDateRange",
  "invalid expiresat": "invalidExpiresat",
  "invalid from/to range": "invalidFromToRange",
  "invalid health sync provider": "invalidHealthSyncProvider",
  "invalid holder userid": "invalidHolderUserid",
  "invalid locationid": "invalidLocationid",
  "invalid membershipid": "invalidMembershipid",
  "invalid national id": "invalidNationalId",
  "invalid or expired reset token": "invalidOrExpiredResetToken",
  "invalid ownerid": "invalidOwnerid",
  "invalid parent id": "invalidParentId",
  "invalid phone number": "invalidPhoneNumber",
  "invalid phone or password": "invalidPhoneOrPassword",
  "invalid refresh token": "invalidRefreshToken",
  "invalid role request id": "invalidRoleRequestId",
  "invalid slot dates": "invalidSlotDates",
  "invalid slug": "invalidSlug",
  "invalid timeoff dates": "invalidTimeoffDates",
  "invalid unfreezeat": "invalidUnfreezeat",
  "kavenegar account is in test mode and can only send sms to the account owner phone. activate the kavenegar account for public otp delivery.": "kavenegarAccountIsInTestModeAndCanOnlySendSmsToTheAccountOwnerPhoneActivateTheKavenegarAccountForPublicOtpDelivery",
  "label is required for other locations": "labelIsRequiredForOtherLocations",
  "ledger entry has no amount": "ledgerEntryHasNoAmount",
  "linkurl is required when linkkind is not none": "linkurlIsRequiredWhenLinkkindIsNotNone",
  "manual payments must use cash, pos, card_to_card, or mixed": "manualPaymentsMustUseCashPosCardToCardOrMixed",
  "media is private": "mediaIsPrivate",
  "membership has expired": "membershipHasExpired",
  "membership holder does not match userid": "membershipHolderDoesNotMatchUserid",
  "membership is not frozen": "membershipIsNotFrozen",
  "membership not found for this club": "membershipNotFoundForThisClub",
  "membership plan is not active": "membershipPlanIsNotActive",
  "membership plan is not published": "membershipPlanIsNotPublished",
  "membership checkout expired": "membershipCheckoutExpired",
  "membership checkout is not pending": "membershipCheckoutIsNotPending",
  "membership checkout preview changed": "membershipCheckoutPreviewChanged",
  "messaging requires an active coach\u2013student relationship": "messagingRequiresAnActiveCoachStudentRelationship",
  "metric value must be an integer": "metricValueMustBeAnInteger",
  "metric value must be finite": "metricValueMustBeFinite",
  "metrickey is required": "metrickeyIsRequired",
  "missing active role": "missingActiveRole",
  "mixed payments require at least two tender rows": "mixedPaymentsRequireAtLeastTwoTenderRows",
  "mixed tender channel must be cash, pos, or card_to_card": "mixedTenderChannelMustBeCashPosOrCardToCard",
  "mixed tender channels must be unique": "mixedTenderChannelsMustBeUnique",
  "national id already registered": "nationalIdAlreadyRegistered",
  "no account role available; use admin authentication": "noAccountRoleAvailableUseAdminAuthentication",
  "no booking dates supplied": "noBookingDatesSupplied",
  "no cancellable bookings in this series": "noCancellableBookingsInThisSeries",
  "no document attached to this request": "noDocumentAttachedToThisRequest",
  "no positive provider_payable balance for period": "noPositiveProviderPayableBalanceForPeriod",
  "no remaining sessions": "noRemainingSessions",
  "no waiting entries to offer": "noWaitingEntriesToOffer",
  "not a member of this club staff": "notAMemberOfThisClubStaff",
  "not a participant of this thread": "notAParticipantOfThisThread",
  "not allowed": "notAllowed",
  "not allowed to access this meal plan": "notAllowedToAccessThisMealPlan",
  "not allowed to access this private resource": "notAllowedToAccessThisPrivateResource",
  "not allowed to access this workout plan": "notAllowedToAccessThisWorkoutPlan",
  "not allowed to modify this resource": "notAllowedToModifyThisResource",
  "not allowed to view this post": "notAllowedToViewThisPost",
  "not an active coach\u2013student relationship": "notAnActiveCoachStudentRelationship",
  "occurrence is in the past": "occurrenceIsInThePast",
  "offer has expired": "offerHasExpired",
  "onlineprovider is required for online delivery": "onlineproviderIsRequiredForOnlineDelivery",
  "only active memberships can be frozen": "onlyActiveMembershipsCanBeFrozen",
  "only active memberships can consume credit": "onlyActiveMembershipsCanConsumeCredit",
  "only active or frozen memberships can be transferred": "onlyActiveOrFrozenMembershipsCanBeTransferred",
  "only active packages can be frozen": "onlyActivePackagesCanBeFrozen",
  "only coach or athlete can message": "onlyCoachOrAthleteCanMessage",
  "only jpeg/png/webp/pdf allowed": "onlyJpegPngWebpPdfAllowed",
  "only linked coaches can view this health assessment": "onlyLinkedCoachesCanViewThisHealthAssessment",
  "option values must be unique": "optionValuesMustBeUnique",
  "otp daily limit reached, try again tomorrow": "otpDailyLimitReachedTryAgainTomorrow",
  "package expired while frozen": "packageExpiredWhileFrozen",
  "package is cancelled": "packageIsCancelled",
  "package is exhausted": "packageIsExhausted",
  "package is expired": "packageIsExpired",
  "package is frozen": "packageIsFrozen",
  "package is not frozen": "packageIsNotFrozen",
  "paidamount cannot exceed the membership payable amount": "paidamountCannotExceedTheMembershipPayableAmount",
  "payer.userid or payer.guest is required": "payerUseridOrPayerGuestIsRequired",
  "payment does not belong to this club": "paymentDoesNotBelongToThisClub",
  "payment authority does not match intent": "paymentAuthorityDoesNotMatchIntent",
  "payment intent is not a gateway payment": "paymentIntentIsNotAGatewayPayment",
  "payment intent is not payable": "paymentIntentIsNotPayable",
  "payment intent not found": "paymentIntentNotFound",
  "payment must be captured to issue invoice": "paymentMustBeCapturedToIssueInvoice",
  "payout is not in dispute": "payoutIsNotInDispute",
  "period.start must be before period.end": "periodStartMustBeBeforePeriodEnd",
  "periodto must be >= periodfrom": "periodtoMustBePeriodfrom",
  "phone already registered": "phoneAlreadyRegistered",
  "planid is required": "planidIsRequired",
  "platform plan code already exists": "platformPlanCodeAlreadyExists",
  "platform plan is not active": "platformPlanIsNotActive",
  "provide refreshtoken or all=true": "provideRefreshtokenOrAllTrue",
  "reason is required (min 3 chars)": "reasonIsRequiredMin3Chars",
  "refresh token reuse detected": "refreshTokenReuseDetected",
  "reject reason is required": "rejectReasonIsRequired",
  "relationshipid must be an active coachstudent for this athlete and coach": "relationshipidMustBeAnActiveCoachstudentForThisAthleteAndCoach",
  "resolutionnote is required when resolving a ticket": "resolutionnoteIsRequiredWhenResolvingATicket",
  "resourceid is required when filtering non-club resource types": "resourceidIsRequiredWhenFilteringNonClubResourceTypes",
  "role cannot list meal plans": "roleCannotListMealPlans",
  "role cannot list workout plans": "roleCannotListWorkoutPlans",
  "role cannot manage meal plans": "roleCannotManageMealPlans",
  "role cannot manage workout plans": "roleCannotManageWorkoutPlans",
  "role not assigned to user": "roleNotAssignedToUser",
  "role request already approved": "roleRequestAlreadyApproved",
  "role request already pending review": "roleRequestAlreadyPendingReview",
  "role request is not pending": "roleRequestIsNotPending",
  "salary is required for employed affiliations": "salaryIsRequiredForEmployedAffiliations",
  "schedule.startsat must be before schedule.endsat": "scheduleStartsatMustBeBeforeScheduleEndsat",
  "selected occurrence is fully booked": "selectedOccurrenceIsFullyBooked",
  "selected slot is no longer available": "selectedSlotIsNoLongerAvailable",
  "session revoked": "sessionRevoked",
  "session role is no longer valid": "sessionRoleIsNoLongerValid",
  "sessionstotal is required for sessions plans": "sessionstotalIsRequiredForSessionsPlans",
  "sharepercent is required for revenue_share affiliations": "sharepercentIsRequiredForRevenueShareAffiliations",
  "slot belongs to a different club": "slotBelongsToADifferentClub",
  "slot has no occurrence on that date": "slotHasNoOccurrenceOnThatDate",
  "slot is no longer available": "slotIsNoLongerAvailable",
  "slot kind does not match the booking": "slotKindDoesNotMatchTheBooking",
  "slot must end after it starts": "slotMustEndAfterItStarts",
  "slot not found or already booked": "slotNotFoundOrAlreadyBooked",
  "slotid is required": "slotidIsRequired",
  "slots must be in the future": "slotsMustBeInTheFuture",
  "social post visibility must be public or followers": "socialPostVisibilityMustBePublicOrFollowers",
  "sourcerecordid or clientmutationid is required": "sourcerecordidOrClientmutationidIsRequired",
  "spaceid is required for space slots": "spaceidIsRequiredForSpaceSlots",
  "startson is required for weekly slots": "startsonIsRequiredForWeeklySlots",
  "status must be approved or rejected": "statusMustBeApprovedOrRejected",
  "student already linked": "studentAlreadyLinked",
  "template key already exists": "templateKeyAlreadyExists",
  "tenders are only allowed when channel is mixed": "tendersAreOnlyAllowedWhenChannelIsMixed",
  "terminal workout logs cannot be patched": "terminalWorkoutLogsCannotBePatched",
  "this code is already taken": "thisCodeIsAlreadyTaken",
  "this occurrence has been cancelled": "thisOccurrenceHasBeenCancelled",
  "this request has already been reviewed": "thisRequestHasAlreadyBeenReviewed",
  "this ticket is closed; open a new ticket instead": "thisTicketIsClosedOpenANewTicketInstead",
  "ticket is already closed": "ticketIsAlreadyClosed",
  "timeoff.to must be after from": "timeoffToMustBeAfterFrom",
  "too many attempts, request a new code": "tooManyAttemptsRequestANewCode",
  "transfer is forbidden for this plan": "transferIsForbiddenForThisPlan",
  "travel is required for home delivery": "travelIsRequiredForHomeDelivery",
  "unknown mock payment": "unknownMockPayment",
  "unknown payment authority": "unknownPaymentAuthority",
  "unknown sport resource": "unknownSportResource",
  "unsupported debt payment channel": "unsupportedDebtPaymentChannel",
  "unsupported checkout consent version": "unsupportedCheckoutConsentVersion",
  "unsupported renewal consent version": "unsupportedRenewalConsentVersion",
  "unsupported subscription consent version": "unsupportedSubscriptionConsentVersion",
  "unsupported top-up channel": "unsupportedTopUpChannel",
  "use coach calendar endpoints for coach blocks": "useCoachCalendarEndpointsForCoachBlocks",
  "use the dedicated completion or skip flow for terminal states": "useTheDedicatedCompletionOrSkipFlowForTerminalStates",
  "user already has an active platform subscription": "userAlreadyHasAnActivePlatformSubscription",
  "paid platform plans require verified gateway checkout": "paidPlatformPlansRequireVerifiedGatewayCheckout",
  "free platform plans do not require gateway checkout": "freePlatformPlansDoNotRequireGatewayCheckout",
  "active platform plan not found": "activePlatformPlanNotFound",
  "platform plan tax exceeds its price": "platformPlanTaxExceedsItsPrice",
  "platform subscription preview changed": "platformSubscriptionPreviewChanged",
  "a subscription checkout is already pending": "subscriptionCheckoutAlreadyPending",
  "subscription checkout is not pending": "subscriptionCheckoutIsNotPending",
  "subscription checkout expired": "subscriptionCheckoutExpired",
  "subscription checkout not found": "subscriptionCheckoutNotFound",
  "user does not have the coach role": "userDoesNotHaveTheCoachRole",
  "verification already pending": "verificationAlreadyPending",
  "waitlist does not belong to this club": "waitlistDoesNotBelongToThisClub",
  "waitlist is full": "waitlistIsFull",
  "wallet owner required for wallet payments": "walletOwnerRequiredForWalletPayments",
  "weekday is required for weekly slots": "weekdayIsRequiredForWeeklySlots",
  "weeklyhours endtime must be after starttime": "weeklyhoursEndtimeMustBeAfterStarttime",
  "window.from must be before window.to": "windowFromMustBeBeforeWindowTo",
  "workout logs must start as draft or in progress": "workoutLogsMustStartAsDraftOrInProgress",
  "wrong current password": "wrongCurrentPassword",
  "you already have a booking for one of these occurrences": "youAlreadyHaveABookingForOneOfTheseOccurrences",
  "you already reviewed this booking": "youAlreadyReviewedThisBooking",
  "you cannot book yourself": "youCannotBookYourself",
  "you cannot change your own status": "youCannotChangeYourOwnStatus",
  "you have already used this coupon": "youHaveAlreadyUsedThisCoupon",
};
