export const discoveryClubsClassDetailBodySectionStyles = {
  root: "flex flex-col gap-8 px-5 pb-4 pt-4",
  section: "flex flex-col gap-3",
  sectionHeader: "flex items-center justify-between gap-3",
  sectionHeaderAside: "flex shrink-0 items-center gap-2",
  sectionTitleRow: "flex min-w-0 flex-1 items-center gap-2",
  sectionTitleIcon: "shrink-0 text-accent",
  sectionTitle: "min-w-0 flex-1 text-foreground",
  seeAll: "cursor-pointer text-sm font-medium text-accent no-underline",
  bodyText: "text-sm leading-relaxed text-muted",
  descriptionWrap: "relative",
  descriptionClamped: "line-clamp-3",
  seeMoreFade: [
    "pointer-events-none absolute inset-x-0 bottom-0 z-10",
    "flex items-end justify-center pb-0.5 pt-10",
    "bg-linear-to-t from-surface via-surface/90 to-transparent",
  ].join(" "),
  seeMoreTrigger: "pointer-events-auto",
  seeLess: "mt-2 flex self-start",
  benefits: "flex flex-col gap-2.5",
  benefitRow: "flex items-start gap-2.5",
  benefitIcon: "mt-0.5 shrink-0 text-success",
  benefitText: "leading-snug text-muted",
  tags: "flex flex-wrap gap-2",
  tag: "h-8 rounded-full border border-border/60 bg-default px-3 shadow-none",
  card: [
    "rounded-[1.5rem] border border-border/60",
    "bg-default px-4 py-4",
  ].join(" "),
  carousel: [
    "min-w-0 -mx-5 w-[calc(100%+2.5rem)] max-w-none overflow-hidden",
    "[-ms-overflow-style:none] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden pe-[calc(env(safe-area-inset-right)+1rem)]",
  ].join(" "),
  carouselTrack: "flex touch-pan-y gap-3 px-5 pb-1",
  slide: "min-w-0 shrink-0",
  amenitySlide: "min-w-0 shrink-0",
  amenityCard: "min-w-[17.5rem] border border-border/60 bg-default shadow-none",
  coachSlide: "w-[min(16.5rem,calc(100vw-4.5rem))] min-w-0 shrink-0",
  coachCard: "w-full",
  equipmentSeeAll: [
    "flex h-[148px] w-[144px] shrink-0 snap-start flex-col items-center justify-center gap-2",
    "rounded-[24px] border border-border/70 bg-default text-foreground",
    "transition-transform duration-fast ease-app",
    "data-[pressed=true]:scale-[0.98]",
  ].join(" "),
  equipmentDrawerBody: "overflow-hidden",
  equipmentDrawerScroll: "max-h-[min(65dvh,32rem)]",
  equipmentDrawerList: "flex flex-col gap-2.5 pb-1",
  seeAllLabel: "text-center text-sm font-semibold",
  gaugeWrap: "flex flex-col items-center gap-2 py-2",
  gaugeFrame: "relative",
  gaugeSvg: "h-auto w-[220px]",
  gaugeCenter:
    "pointer-events-none absolute inset-x-0 top-[48%] -translate-y-1/2 text-center",
  gaugeRange:
    "text-[1.65rem] leading-none tracking-tight text-foreground tabular-nums",
  gaugeUnit: "mt-1 text-xs text-muted",
  gaugeCaption: "text-center text-sm text-muted",
  intensityRow: "flex items-start gap-3",
  intensityIconWrap: [
    "flex size-12 shrink-0 items-center justify-center rounded-2xl",
    "bg-success/15 text-success",
  ].join(" "),
  intensityCopy: "min-w-0 flex-1",
  intensityScoreRow: "flex flex-wrap items-baseline gap-2",
  intensityScore: "text-[1.75rem] leading-none tracking-tight text-foreground",
  intensityLabel: "font-medium text-success",
  intensityDescription: "mt-1.5 leading-relaxed text-muted",
  timeline: "relative flex flex-col gap-5 ps-1",
  timelineItem: "relative flex gap-3",
  timelineRail: [
    "absolute start-[0.55rem] top-3 bottom-[-1.25rem] w-px",
    "bg-accent/35",
  ].join(" "),
  timelineDot: [
    "relative z-10 mt-1.5 size-2.5 shrink-0 rounded-full",
    "bg-accent ring-4 ring-accent/15",
  ].join(" "),
  timelineBody: "min-w-0 flex-1",
  timelineTitle: "text-foreground",
  timelineText: "mt-1 leading-relaxed text-muted",
  related: [
    "min-w-0 -mx-5 w-[calc(100%+2.5rem)] max-w-none overflow-hidden",
    "[-ms-overflow-style:none] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden pe-[calc(env(safe-area-inset-right)+1rem)]",
  ].join(" "),
  relatedTrack: "flex touch-pan-y gap-3 px-5 pb-1",
  relatedCard: [
    "block w-[min(16.5rem,calc(100vw-4.5rem))] shrink-0 overflow-hidden rounded-[1.35rem] text-start no-underline",
    "border border-border/60 bg-default p-2.5 shadow-none",
    "transition-transform duration-fast ease-app active:scale-[0.98]",
  ].join(" "),
  relatedMedia:
    "relative mb-2.5 h-28 w-full overflow-hidden rounded-[1.1rem] bg-surface",
  relatedImage: "object-cover",
  relatedCategory: [
    "mb-1.5 h-6 rounded-full border-0 px-2",
    "[--chip-bg:color-mix(in_oklch,var(--accent)_14%,transparent)]",
    "[--chip-fg:var(--accent)]",
    "[&_.chip__label]:text-xs [&_.chip__label]:font-semibold",
  ].join(" "),
  relatedTitle: "line-clamp-2 text-foreground",
  relatedMeta: "mt-2 flex items-center gap-3 text-muted",
  relatedMetaItem: "inline-flex items-center gap-1",
  relatedMetaIcon: "shrink-0",
} as const;
