export const discoveryClubsClassDetailBodySectionStyles = {
  root: "mx-auto w-full max-w-lg px-4 pt-5",
  tabs: "w-full",
  tabsListContainer: "rounded-none bg-transparent",
  tabsList: [
    "mx-auto w-full max-w-xs rounded-full border-0 bg-default p-1",
    "**:data-[slot=tabs-tab]:h-10",
    "**:data-[slot=tabs-tab]:flex-1",
    "**:data-[slot=tabs-tab]:rounded-full",
    "**:data-[slot=tabs-tab]:bg-transparent",
    "**:data-[slot=tabs-tab]:text-sm",
    "**:data-[slot=tabs-tab]:font-medium",
    "**:data-[slot=tabs-tab]:text-muted",
    "**:data-[slot=tabs-tab]:opacity-100",
    "**:data-[slot=tabs-tab]:shadow-none",
    "**:data-[slot=tabs-tab]:data-[selected=true]:text-foreground",
    "**:data-[slot=tabs-indicator]:rounded-full",
    "**:data-[slot=tabs-indicator]:bg-surface",
    "**:data-[slot=tabs-indicator]:shadow-sm",
  ].join(" "),
  panel: "flex flex-col gap-7 pt-6",
  section: "flex flex-col gap-3",
  sectionTitle: "text-foreground",
  sectionHeader: "flex items-center justify-between gap-3",
  seeAll: "cursor-pointer text-sm font-medium text-stats-orange no-underline",
  bodyText: "leading-relaxed text-muted",
  benefits: "flex flex-col gap-2.5",
  benefitRow: "flex items-start gap-2.5",
  benefitIcon: "mt-0.5 shrink-0 text-success",
  benefitText: "leading-snug text-muted",
  tags: "flex flex-wrap gap-2",
  tag: [
    "h-8 rounded-full border-0 px-3",
    "[--chip-bg:var(--default)]",
    "[--chip-fg:var(--muted)]",
    "[&_.chip__label]:font-medium",
  ].join(" "),
  gallery: "flex gap-2.5 overflow-x-auto pb-1 [-ms-overflow-style:none] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden",
  galleryItem:
    "relative h-20 w-24 shrink-0 overflow-hidden rounded-2xl bg-default",
  galleryImage: "object-cover",
  card: [
    "rounded-[1.5rem] border border-border/70 bg-surface p-4",
    "shadow-[0_4px_20px_color-mix(in_oklch,var(--foreground)_6%,transparent)]",
  ].join(" "),
  gaugeWrap: "flex flex-col items-center gap-2 py-2",
  gaugeSvg: "h-auto w-[220px]",
  gaugeCenter: "pointer-events-none absolute inset-x-0 top-[42%] -translate-y-1/2 text-center",
  gaugeRange: "text-[1.65rem] leading-none tracking-tight text-foreground",
  gaugeUnit: "mt-1 text-xs text-muted",
  gaugeCaption: "text-center text-sm text-muted",
  intensityRow: "flex items-start gap-3",
  intensityIconWrap: [
    "flex size-12 shrink-0 items-center justify-center rounded-2xl",
    "bg-success/15 text-success",
  ].join(" "),
  intensityCopy: "min-w-0 flex-1",
  intensityScoreRow: "flex flex-wrap items-baseline gap-2",
  intensityScore: "text-[1.75rem] leading-none tracking-tight text-foreground",
  intensityLabel: "font-medium text-success",
  intensityDescription: "mt-1.5 leading-relaxed text-muted",
  timeline: "relative flex flex-col gap-5 ps-1",
  timelineItem: "relative flex gap-3",
  timelineRail: [
    "absolute start-[0.55rem] top-3 bottom-[-1.25rem] w-px",
    "bg-stats-orange/35",
  ].join(" "),
  timelineDot: [
    "relative z-10 mt-1.5 size-2.5 shrink-0 rounded-full",
    "bg-stats-orange ring-4 ring-stats-orange/15",
  ].join(" "),
  timelineBody: "min-w-0 flex-1",
  timelineTitle: "text-foreground",
  timelineText: "mt-1 leading-relaxed text-muted",
  related: "flex gap-3 overflow-x-auto pb-1 [-ms-overflow-style:none] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden",
  relatedCard: [
    "block w-[260px] shrink-0 overflow-hidden rounded-[1.35rem] text-start no-underline",
    "border border-border/70 bg-surface p-2.5",
    "shadow-[0_4px_18px_color-mix(in_oklch,var(--foreground)_6%,transparent)]",
    "transition-transform duration-fast ease-app active:scale-[0.98]",
  ].join(" "),
  relatedMedia:
    "relative mb-2.5 h-28 w-full overflow-hidden rounded-[1.1rem] bg-default",
  relatedImage: "object-cover",
  relatedCategory: [
    "mb-1.5 h-6 rounded-full border-0 px-2",
    "[--chip-bg:color-mix(in_oklch,var(--stats-orange)_14%,transparent)]",
    "[--chip-fg:var(--stats-orange)]",
    "[&_.chip__label]:text-xs [&_.chip__label]:font-semibold",
  ].join(" "),
  relatedTitle: "line-clamp-2 text-foreground",
  relatedMeta: "mt-2 flex items-center gap-3 text-muted",
  relatedMetaItem: "inline-flex items-center gap-1",
  relatedMetaIcon: "shrink-0",
} as const;
