export const routes = {
  signIn: "/sign-in",
  dashboard: "/dashboard",
  clubs: "/clubs",
  members: "/members",
  bookings: "/bookings",
  bookingCreate: "/bookings/new",
  bookingCheckIn: "/bookings/check-in",
  bookingReschedule: "/bookings/reschedule",
  bookingCancel: "/bookings/cancel",
  finance: "/finance",
  staff: "/staff",
  operations: "/operations",
  settings: "/settings",
  clubCreate: "/clubs/new",
  branchCreate: "/clubs/branches/new",
  staffInvite: "/staff/invite",
  resourceCreate: "/operations/resources/new",
  offeringCreate: "/operations/offerings/new",
  announcementCreate: "/settings/announcements/new",
  settlementCreate: "/finance/settlements/new",
} as const;
