export const coachProgramsScreenStyles = {
  root: "bg-background",
  content: "flex flex-col gap-6 pb-10 pt-1",
  intro: "flex flex-col gap-2",
  introTitle: "tracking-tight text-foreground",
  introSubtitle: "text-muted",
  list: "flex flex-col gap-4",
  card: "flex flex-col gap-3 rounded-[24px] border border-border bg-surface p-4",
  cardTop: "flex items-start justify-between gap-2",
  cardTitle: "text-foreground",
  cardFocus: "text-muted",
  metaRow: "flex flex-wrap items-center gap-x-4 gap-y-1.5",
  metaItem: "inline-flex items-center gap-1.5 text-muted",
  metaIcon: "shrink-0 text-muted",
  updated: "text-muted",
  empty:
    "flex flex-col items-center gap-2 rounded-[24px] border border-border bg-surface px-6 py-10 text-center",
  emptyTitle: "text-foreground",
  emptyBody: "text-muted",
  form: "flex flex-col gap-3 rounded-[24px] border border-border bg-surface p-4",
  formActions: "mt-1 flex gap-2",
} as const;
