export const seoClassDetailScreenStyles = {
  root: "min-h-[70dvh] bg-background px-4 py-10 text-foreground sm:px-6 sm:py-14 lg:px-8 lg:py-16",
  article: "mx-auto flex w-full min-w-0 max-w-4xl flex-col gap-8",
  hero: "space-y-4 border-b border-border pb-8",
  eyebrow: "text-sm font-medium text-accent",
  title: "text-balance text-3xl font-bold tracking-tight sm:text-4xl lg:text-5xl",
  description: "max-w-3xl whitespace-pre-line text-sm leading-8 text-foreground/85 sm:text-base",
  layout: "grid gap-8 lg:grid-cols-[minmax(0,1fr)_18rem]",
  content: "space-y-8",
  section: "space-y-4",
  sectionTitle: "text-xl font-bold",
  schedule: "grid gap-3 sm:grid-cols-2",
  occurrence: "rounded-2xl border border-border bg-surface p-4",
  occurrenceDate: "font-semibold",
  occurrenceMeta: "mt-2 flex flex-wrap gap-x-3 gap-y-1 text-sm text-muted",
  available: "mt-3 text-sm font-medium text-success",
  full: "mt-3 text-sm font-medium text-danger",
  empty: "rounded-2xl border border-border p-5 text-sm text-muted",
  timezone: "text-xs text-muted",
  aside: "h-fit space-y-4 rounded-3xl border border-border bg-surface p-5 lg:sticky lg:top-28",
  clubLabel: "text-sm text-muted",
  clubName: "text-lg font-bold",
  primaryCta: "flex min-h-12 items-center justify-center rounded-full bg-accent px-5 text-center font-bold text-accent-foreground",
  secondaryCta: "flex min-h-11 items-center justify-center rounded-full border border-border px-5 text-center text-sm font-semibold",
} as const;
