import type { LocationKind, RefType, SportKind } from "@repo/api";

export const routes = {
  signIn: "/sign-in",
  otp: "/otp",
  forgotPassword: "/forgot-password",
  dashboard: "/dashboard",
  analytics: "/analytics",
  users: "/dashboard/users",
  usersKyc: "/dashboard/users/kyc",
  usersCoachVerifications: "/dashboard/users/coach-verifications",
  usersClubReviews: "/dashboard/users/club-reviews",
  user: (userId: string) => `/dashboard/users/${userId}`,
  usersNew: "/dashboard/users/new",
  clubs: "/dashboard/clubs",
  clubsNew: "/dashboard/clubs/new",
  club: (clubId: string) => `/dashboard/clubs/${clubId}`,
  clubEdit: (clubId: string) => `/dashboard/clubs/${clubId}/edit`,
  clubSlotNew: (clubId: string) => `/dashboard/clubs/${clubId}/slots/new`,
  clubSlotEdit: (clubId: string, slotId: string) =>
    `/dashboard/clubs/${clubId}/slots/${slotId}/edit`,
  locations: (kind: LocationKind = "country") =>
    `/dashboard/locations/${kind}`,
  locationNew: (kind: LocationKind) => `/dashboard/locations/${kind}/new`,
  locationEdit: (kind: LocationKind, locationId: string) =>
    `/dashboard/locations/${kind}/${locationId}/edit`,
  sports: (kind: SportKind = "category") => `/dashboard/sports/${kind}`,
  sportNew: (kind: SportKind) => `/dashboard/sports/${kind}/new`,
  sportEdit: (kind: SportKind, sportId: string) =>
    `/dashboard/sports/${kind}/${sportId}/edit`,
  choices: "/dashboard/choices",
  choicesNew: "/dashboard/choices/new",
  choiceEdit: (key: string) => `/dashboard/choices/${encodeURIComponent(key)}/edit`,
  refs: (type: RefType = "equipment") => `/dashboard/refs/${type}`,
  refNew: (type: RefType) => `/dashboard/refs/${type}/new`,
  refEdit: (type: RefType, refId: string) =>
    `/dashboard/refs/${type}/${refId}/edit`,
  support: "/dashboard/support",
  supportFaq: "/dashboard/support/faq",
  supportFaqNew: "/dashboard/support/faq/new",
  supportFaqEdit: (faqId: string) => `/dashboard/support/faq/${faqId}/edit`,
  articles: "/dashboard/articles",
  articlesNew: "/dashboard/articles/new",
  articleEdit: (articleId: string) => `/dashboard/articles/${articleId}/edit`,
  banners: "/dashboard/banners",
  bannersNew: "/dashboard/banners/new",
  bannerEdit: (bannerId: string) => `/dashboard/banners/${bannerId}/edit`,
  gamification: "/dashboard/gamification",
  achievementNew: "/dashboard/gamification/new",
  achievementEdit: (achievementId: string) =>
    `/dashboard/gamification/${achievementId}/edit`,
  gamificationRules: "/dashboard/gamification/rules",
  pointRuleNew: "/dashboard/gamification/rules/new",
  pointRuleEdit: (ruleId: string) =>
    `/dashboard/gamification/rules/${ruleId}/edit`,
  gamificationLedger: "/dashboard/gamification/ledger",
  financeLedger: "/dashboard/finance/ledger",
  financePayments: "/dashboard/finance/payments",
  financePayouts: "/dashboard/finance/payouts",
  financeRefunds: "/dashboard/finance/refunds",
  bookings: "/dashboard/bookings",
  catalogPlans: "/dashboard/catalog/plans",
  catalogPlanNew: "/dashboard/catalog/plans/new",
  catalogPlanEdit: (planId: string) => `/dashboard/catalog/plans/${planId}/edit`,
  catalogFood: "/dashboard/catalog/food",
  catalogFoodNew: "/dashboard/catalog/food/new",
  catalogFoodEdit: (foodId: string) => `/dashboard/catalog/food/${foodId}/edit`,
  catalogExercises: "/dashboard/catalog/exercises",
  catalogExerciseNew: "/dashboard/catalog/exercises/new",
  catalogExerciseEdit: (exerciseId: string) =>
    `/dashboard/catalog/exercises/${exerciseId}/edit`,
  catalogMetrics: "/dashboard/catalog/metrics",
  catalogMetricNew: "/dashboard/catalog/metrics/new",
  catalogMetricEdit: (metricId: string) =>
    `/dashboard/catalog/metrics/${metricId}/edit`,
  catalogCoaching: "/dashboard/catalog/coaching",
  opsSocial: "/dashboard/ops/social",
  opsAudit: "/dashboard/ops/audit",
  opsTemplates: "/dashboard/ops/templates",
  opsTemplateEdit: (templateKey: string) =>
    `/dashboard/ops/templates/${encodeURIComponent(templateKey)}/edit`,
} as const;
