import type { UseOnboardingReturn } from "@/modules/app/lib/use-onboarding";

export type OnboardingCarouselSectionProps = Pick<
  UseOnboardingReturn,
  | "t"
  | "slide"
  | "age"
  | "fullName"
  | "gender"
  | "genderOther"
  | "birthdate"
  | "heightCm"
  | "heightUnit"
  | "weightKg"
  | "weightUnit"
  | "bodyType"
  | "sleep"
  | "mood"
  | "activities"
  | "diet"
  | "calories"
  | "goals"
  | "bloodGroup"
  | "bloodRh"
  | "avatar"
  | "identityValue"
  | "identityLabels"
  | "provinces"
  | "phaseSteps"
  | "goalOptions"
  | "genderOptions"
  | "bodyTypeOptions"
  | "sleepOptions"
  | "activityOptions"
  | "moodOptions"
  | "dietOptions"
  | "setFullName"
  | "setGender"
  | "setGenderOther"
  | "setBirthdate"
  | "setHeightCm"
  | "setHeightUnit"
  | "setWeightKg"
  | "setWeightUnit"
  | "setBodyType"
  | "setSleep"
  | "setMood"
  | "setDiet"
  | "setBloodGroup"
  | "setBloodRh"
  | "patchIdentity"
  | "uploadAvatar"
  | "choosePremadeAvatar"
  | "toggleGoal"
  | "toggleActivity"
  | "handleCaloriesChange"
  | "requestFinish"
> & {
  emblaRef: UseOnboardingReturn["emblaRef"];
  carouselClassName?: string;
  trackClassName?: string;
};
