export const discoveryCoachesDetailScreenStyles = {
  root: "relative min-h-dvh w-full bg-background text-foreground",
  scroll: [
    "flex min-h-dvh flex-col gap-4",
    "pb-[calc(9.5rem+env(safe-area-inset-bottom))]",
  ].join(" "),
  tabsWrap: "mx-auto w-full max-w-lg px-5",
  tabs: "w-full",
  tabsListContainer: "rounded-none bg-transparent",
  tabsList: [
    "mx-auto w-full max-w-xs rounded-full border-0 bg-default p-1",
    "**:data-[slot=tabs-tab]:h-10",
    "**:data-[slot=tabs-tab]:flex-1",
    "**:data-[slot=tabs-tab]:rounded-full",
    "**:data-[slot=tabs-tab]:bg-transparent",
    "**:data-[slot=tabs-tab]:text-sm",
    "**:data-[slot=tabs-tab]:font-medium",
    "**:data-[slot=tabs-tab]:text-muted",
    "**:data-[slot=tabs-tab]:opacity-100",
    "**:data-[slot=tabs-tab]:shadow-none",
    "**:data-[slot=tabs-tab]:data-[selected=true]:text-foreground",
    "**:data-[slot=tabs-indicator]:rounded-full",
    "**:data-[slot=tabs-indicator]:bg-surface",
    "**:data-[slot=tabs-indicator]:shadow-sm",
  ].join(" "),
  panel: "flex flex-col gap-7 pt-5 pb-4",
} as const;
